# -*- coding: utf8 -*-


g_chinese_l = [
               
               "初",
               
                "属性修改", 
                 "控制状态", 
                 "施放技能", 
                 "免疫状态", 
                 "消失触发", 
                 "怒气", 
                 "生命", 
                 "体力", 
                 "物理防御", 
                 "物理攻击", 
                 "法术攻击", 
                 "法术防御", 
                 "技能攻击", 
                 "技能防御", 
                 "爆击值", 
                 "闪避值", 
                 "命中值", 
                 "反击值", 
                 "格挡值", 
                 "破挡值", 
                 "晕眩", 
                 "混乱", 
                 "免伤", 
                 "数值", 
                 "最大值千分比", 
                 "当前值千分比", 
                 "减少", 
                 "增加", 
                 "是", 
                 "否",
                 "骑士", 
                 "剑士", 
                 "弓手", 
                 "法师", 
                 "武僧", 
                 "刺客", 
                 "狂战", 
                 "祭司", 
                 "先知", 
                 "全职业", 
                 "白色", 
                 "绿色", 
                 "蓝色", 
                 "紫色", 
                 "金色", 
                 "红色", 
                 "目标", 
                 "自己", 
                 "单人", 
                 "后方", 
                 "横向直线", 
                 "纵向直线", 
                 "全体", 
                 "十字", 
                 "后方纵向直线", 
                 "随机",
                 "前排",
                 "后排",
                 "生命最少",
                 "近程", 
                 "远程", 
                 "飞行", 
                 "物理伤害", 
                 "法术伤害", 
                 "技能伤害", 
                 "回复生命", 
                 "回复怒气", 
                 "上沿触发", 
                 "间隔触发", 
                 "头部", 
                 "身体", 
                 "腿部", 
                 "鞋子", 
                 "手套", 
                 "护具", 
                 "翅魂（一）",
                 "翅魂（二）",
                 "翅魂（三）",
                 "翅魂（四）",
                 "翅魂（五）",
                 "翅魂（六）",
                 "翅魂（七）",
                 "翅魂（八）",
                 "灵翅",
                 "固定礼包", 
                 "随机礼包", 
                 "碎片",
                 "功勋", 
                 "金币", 
                 "物品", 
                 "声望", 
                 "伙伴", 
                 "钻石", 
                 "经验",
                 "激活一套翅膀",
                 "普通", 
                 "神将",
                 "品质",
                 "品质等级",
                 "每日登录",
                 "累积充值一",
                 "累积充值二",
                 "累积充值三",
                 "累积充值四",
                 "首次充值",
                 "等级奖励",
                 "通关奖励一",
                 "通关奖励二",
                 "通关奖励三",
                 "通关奖励四",
                 "钻石周卡",
                 "金币周卡",
                 "任意普通副本",
                 "任意精英副本",
                 "任意神将副本",
                 "任意心魔副本",
                 "任意击杀怪物",
                 "任意装备材料",
                 "任意翅魂材料",
                 "任意装备图纸",
                 "任意球员碎片",
                 "任意装备强化",
                 "任意球员升级",
                 "竞技场挑战",
                 "球员试炼",
                 "任意征战图纸",
                 "任意光芒图纸",
                 "任意星耀图纸",
                 "对话",
                 "日常",
                 "周常",
                 "天族",
                 "圣族",
                 "精灵",
                 "降级",
                 "消失",
                 "清零",
                 "安全级",
                 "财神",
                 "新服充值",
                 "新服等级",
                 "新服实力排行",
                 "新服球星排行",
                 "新服奖杯排行",
                 "新服等级排行",
                 "每日",
                 "单次",
                 "账号认证",
                 "管理控制",
                 "业务主机",
                 "业务从机",
                 "集合业务",
                 "生命类",
                 "怒气类",
                 "物理攻击类",
                 "魔法攻击类",
                 "物理防御类",
                 "魔法防御类",
                 "命中等级类",
                 "见习勇士",
                 "勇士",
                 "见习士兵",
                 "士兵",
                 "见习中尉",
                 "中尉",
                 "骑尉",
                 "都尉",
                 "勋爵",
                 "男爵",
                 "子爵",
                 "伯爵",
                 "侯爵",
                 "公爵",
                 "王爵",
                 "限定万魔塔",
                 "无限万魔塔",
                
                 "神佑",
                 "连击",
                 "反震",
                 "合击",
                 "反击",  
                 "韧性值",
                 "暴击伤害",
                 "物理伤害结果",
                 "生命上限",
                 "当前生命",
                 "反震伤害",
                 "触发概率",
                 "增加值",
                 "等级增加值",
                 "结果百分比",
                 "增加百分比",
                 "减少百分比",
                 "增加数值",
                 "减少数值",
                 "死亡时",
                 "普攻时",
                 "受近战普攻时",
                 "受普攻时",
                 "开战前",
                 "技能已触发",
                 "法术攻击时",
                 "物理攻击时",
                 "合击选择时",
                 "被克制",
                 "系统公告",
                 "滚动条公告",
                 "光",
                 "暗",
                 "地",
                 "水",
                 "火",
                 "风",
                 "无",
                 "白名",
                 "红名",
                 "黑名",
                 "物法攻击",
                 "每日活动",
                 "每周活动",
                 "每月活动",
                 "付费开启",
                 "结拜返利",
                 "结拜充值",
                 "帮派日常",
                 "帮派建设",
                 "礼包",
                 "单次活动",
                 "充值限量",
                 "活动充值送球员",
                 "活动充值送灵翅",
                 "新活动充值送球员",
                 "新活动充值送灵翅",
                 "充值送礼",
                 "刷新碎片",
                 "活动球员",
                 "订单回调服务",
                 "消费限量",
                 "B金币",
                 "B钻石",
                 "B物品",
                 "B球员",
                 "门将（左）",
                 "后卫一（左）",
                 "后卫二（左）",
                 "后卫三（左）",
                 "中场一（左）",
                 "中场二（左）",
                 "中场三（左）",
                 "中场四（左）",
                 "前场一（左）",
                 "前场二（左）",
                 "前场三（左）",
                 "开球一（左）",
                 "开球二（左）",
                 "门将（右）",
                 "后卫一（右）",
                 "后卫二（右）",
                 "后卫三（右）",
                 "中场一（右）",
                 "中场二（右）",
                 "中场三（右）",
                 "中场四（右）",
                 "前场一（右）",
                 "前场二（右）",
                 "前场三（右）",
                 "开球一（右）",
                 "开球二（右）",
                 "不失球获得胜利",
                 "限定球员数量取胜",
                 "单人单场进多球",
                 "限定分差取胜",
                 "限定进球取胜",
                 "按时间随机触发",
                 "射门时触发",
                 "守门时触发",
                 "传球时触发",
                 "过人时触发",
                 "带球时触发",
                 "防守时触发",
                 "加状态",
                 "时间暂停",
                 "吊射",
                 "传球",
                 "己方全体",
                 "对方全体",
                 "足球自己",
                 "当前带球人",
                 "己方门将",
                 "对方门将",
                 "足球全体",
                 "周围敌人",
                 "射门",
                 "平衡",
                 "控球",
                 "技能属性传球",
                 "干扰",
                 "侵犯",
                 "抢断",
                 "拦截",
                 "扑救",
                 "手控球",
                 "速度",
                 "体力伤害",
                 "进攻",
                 "防守",
                 "守门",
                 "昏迷",
                 "足球混乱",
                 "数值类型",
                 "数值枚举类型",
                 "普通联赛",
                 "巨星对决",
                 "指定比赛获胜",
                 "任意球员训练次数",
                 "获得奖杯",
                 "指定类型比赛",
                 "进球数",
                 "球员实力达到指定值",
                 "获得指定品质球员",
                 "相等",
                 "大于或等于",
                 "任意球员升级次数",
                 "球员",
                 "道具",
                 "前场",
                 "中场",
                 "后场",
                 "门将",
                 "充值排行",

               #情感倾向
               "鼓励",
                "安抚",
                "赞美",
                "告白",
                "逃避",
                "吐槽",
                "挑逗",
                "同意",
                "否认",
                "贿赂",
                "搭讪",
                "追问",
                "倾诉",
                #话题池
                "时事",
                "美食",
                "故事模式",
                #称号
                "屌丝",
                #场景
                "食堂",
                "操场",
                "教室",
                "大门",
                #奖励类型
                "好感度",
                "货物",
                "触发对话",
                
                #npc名字
                "一号女主",
                "二号女主",
                "三号女主",
                "小橙",
                "柿子",
                "所有人",

                #动作
                "待机",
                "点头",
                "摇头",
                "偏头",
                "喜悦",
                "生气",
                "不高兴",
                "吃惊",
                "失望",
                "满足",
                "大吃惊",
                "我想回家",
                "大生气",
                "败给你了",
                "摇晃",
                "talk_nv1",
                "talk_nv10",
                "talk_nv12",
                "talk_nv3",
                "talk_nv5",
                "talk_nv8",


                #判断
#                "是",
#                "否",
                
                #道具
                "红色被子",
                "iPhone5",
                "康熙字典",
                "百元",
                "康师傅红烧牛肉面",

                #谈话索引
                "收到礼物",
                "唉",
                "妈妈礼物",
                "你想什么",
                "爸爸送书",
                "满头雾水",


]

g_enum_define={
 "初":"E_NOTHING",
 
  "属性修改":"E_BUFF_EFFECT_ATTR_CHANGE", 
 "控制状态":"E_BUFF_EFFECT_STATE_CONTROL", 
 "施放技能":"E_BUFF_EFFECT_CAST_SKILL", 
 "免疫状态":"E_BUFF_EFFECT_IMMUNE", 
 "消失触发":"E_BUFF_EFFECT_TRIGGER_WHEN_DISAPPEAR", 
 "怒气":"E_BASIC_ATTR_ANGER", 
 "生命":"E_BASIC_ATTR_HP", 
 "体力":"E_BASIC_ATTR_CD", 
 "物理防御":"E_BASIC_ATTR_PSYDEF", 
 "物理攻击":"E_BASIC_ATTR_PSYATK", 
 "法术攻击":"E_BASIC_ATTR_MAGIATK", 
 "法术防御":"E_BASIC_ATTR_MAGIDEF", 
 "技能攻击":"E_BASIC_ATTR_SKILLATK", 
 "技能防御":"E_BASIC_ATTR_SKILLDEF", 
 "爆击值":"E_BASIC_ATTR_CRIT", 
 "闪避值":"E_BASIC_ATTR_DODGE", 
 "命中值":"E_BASIC_ATTR_ACCURATE", 
 "反击值":"E_BASIC_ATTR_COUNTERSTRIKE", 
 "格挡值":"E_BASIC_ATTR_BLOCK", 
 "破挡值":"E_BASIC_ATTR_BREAK_BLOCK", 
 "晕眩":"E_STATE_DAZE", 
 "混乱":"E_STATE_CHAOS", 
 "免伤":"E_AVOID_HARM", 
 "数值":"E_NUMERIC", 
 "最大值千分比":"E_PERCENT_THOUSAND_MAX", 
 "当前值千分比":"E_PERCENT_THOUSAND_CURRENT", 
 "减少":"E_DEC", 
 "增加":"E_ADD", 
 "是":"E_YES", 
 "否":"E_NO", 
 "骑士":"E_PROFESSION_KNIGHT", 
 "剑士":"E_PROFESSION_SWARDMAN", 
 "弓手":"E_PROFESSION_ARCHER", 
 "法师":"E_PROFESSION_ENCHANTER", 
 "武僧":"E_PROFESSION_MONK_WARRIOR", 
 "刺客":"E_PROFESSION_ASSASSIN", 
 "狂战":"E_PROFESSION_BERSERKER", 
 "祭司":"E_PROFESSION_FLAMEN", 
 "先知":"E_PROFESSION_ORACLE", 
 "全职业":"E_PROFESSION_ALL", 
 "白色":"E_ITEM_COLOR_WHITE", 
 "绿色":"E_ITEM_COLOR_GREEN", 
 "蓝色":"E_ITEM_COLOR_BLUE", 
 "紫色":"E_ITEM_COLOR_PURPLE", 
 "金色":"E_ITEM_COLOR_GOLDEN", 
 "红色":"E_ITEM_COLOR_RED", 
 "目标":"E_TARGET_TARGET", 
 "自己":"E_TARGET_SELF", 
 "单人":"E_SCALE_SINGLE", 
 "后方":"E_SCALE_BACK", 
 "横向直线":"E_SCALE_ROW", 
 "纵向直线":"E_SCALE_COLUM", 
 "随机":"E_SCALE_RANDOM",
 "前排":"E_SCALE_FRONTLINE",
 "后排":"E_SCALE_BACKLINE",
 "生命最少":"E_SCALE_LOWEST_HP",
 "全体":"E_SCALE_ALL", 
 "十字":"E_SCALE_CROSS", 
 "后方纵向直线":"E_SCALE_BACK_COLUM", 
 "近程":"E_NEAR", 
 "远程":"E_FAR", 
 "飞行":"E_FLY", 
 "物理伤害":"E_PSY_HURT", 
 "法术伤害":"E_MAGI_HURT", 
 "技能伤害":"E_SKILL_HURT", 
 "回复生命":"E_RECOVER_HP", 
 "回复怒气":"E_RECOVER_ANGER", 
 "上沿触发":"E_TRIGGER_UP", 
 "间隔触发":"E_TRIGGER_TIMER", 
 "头部":"E_PART_HELMET", 
 "身体":"E_PART_JERSEY", 
 "腿部":"E_PART_TROUSER", 
 "鞋子":"E_PART_SHOE", 
 "手套":"E_PART_GLOVES", 
 "护具":"E_PART_PROTECT", 
 "翅魂（一）":"E_PART_WING_1",
 "翅魂（二）":"E_PART_WING_2",
 "翅魂（三）":"E_PART_WING_3",
 "翅魂（四）":"E_PART_WING_4",
 "翅魂（五）":"E_PART_WING_5",
 "翅魂（六）":"E_PART_WING_6",
 "翅魂（七）":"E_PART_WING_7",
 "翅魂（八）":"E_PART_WING_8",
 "灵翅":"E_PART_WING",
 "固定礼包":"E_OBJ_GIFT_PACKET_FIXED", 
 "随机礼包":"E_OBJ_GIFT_PACKET", 
 "碎片":"E_OBJ_FRAGMENT", 
 "功勋":"E_OBJ_EXPLOIT", 
 "金币":"E_OBJ_GOLD", 
 "物品":"E_OBJ_ITEM", 
 "声望":"E_OBJ_POPULARITY", 
 "伙伴":"E_OBJ_MATE", 
 "钻石":"E_OBJ_DIAMOND", 
 "经验":"E_OBJ_EXP",
 "普通":"E_MATE_QUALITY_BAD", 
 "神将":"E_MATE_QUALITY_GOOD", 
 "品质":"E_ENFORCE_TYPE_Q",
 "品质等级":"E_ENFORCE_TYPE_QL",
 "每日登录":"E_CHARGE_CONDITION_DAILY_LOGIN",
 "累积充值一":"E_CHARGE_CONDITION_CHARGE_ACCUMULATE_1",
 "累积充值二":"E_CHARGE_CONDITION_CHARGE_ACCUMULATE_2",
 "累积充值三":"E_CHARGE_CONDITION_CHARGE_ACCUMULATE_3",
 "累积充值四":"E_CHARGE_CONDITION_CHARGE_ACCUMULATE_4",
 "首次充值":"E_CHARGE_CONDITION_CHARGE_FIRST",
 "等级奖励":"E_CHARGE_CONDITION_LEVEL",
 "通关奖励一":"E_CHARGE_CONDITION_FINISHED_FUBEN_1",
 "通关奖励二":"E_CHARGE_CONDITION_FINISHED_FUBEN_2",
 "通关奖励三":"E_CHARGE_CONDITION_FINISHED_FUBEN_3",
 "通关奖励四":"E_CHARGE_CONDITION_FINISHED_FUBEN_4",
 "激活一套翅膀":"E_CHARGE_PRIZE_ACTIVATE_WRING_SUIT",
 "钻石周卡":"E_CHARGE_PRIZE_WEEK_DIAMOND",
 "金币周卡":"E_CHARGE_PRIZE_WEEK_GOLD",
 "任意普通副本":"E_LOOP_TASK_TYPE_ANY_NORMAL_FUBEN",
 "任意精英副本":"E_LOOP_TASK_TYPE_ANY_HARD_FUBEN",
 "任意神将副本":"E_LOOP_TASK_TYPE_ANY_SHENJIANG_FUBEN",
 "任意心魔副本":"E_LOOP_TASK_TYPE_ANY_XINMO_FUBEN",
 "任意击杀怪物":"E_LOOP_TASK_TYPE_ANY_KILL_MONSTER",
 "任意装备材料":"E_LOOP_TASK_TYPE_ANY_EQUIPMENT_MATERIAL",
 "任意翅魂材料":"E_LOOP_TASK_TYPE_ANY_WING_MATERIAL",
 "任意装备图纸":"E_LOOP_TASK_TYPE_ANY_EQUIPMENT_FORMULA",
 "任意球员碎片":"E_LOOP_TASK_TYPE_ANY_MATE_FRAGMENT",
 "任意装备强化":"E_LOOP_TASK_TYPE_ANY_EQUIPMENT_STRENGTHEN",
 "任意球员升级":"E_LOOP_TASK_TYPE_ANY_MATE_LEVELUP",
 "竞技场挑战":"E_LOOP_TASK_TYPE_ANY_ROLE_ARENA",
 "球员试炼":"E_LOOP_TASK_TYPE_ANY_MATE_TRAIN",
 "任意征战图纸":"E_LOOP_TASK_TYPE_ANY_GREEN_ZHENGZHAN",
 "任意光芒图纸":"E_LOOP_TASK_TYPE_ANY_GREEN_GUANGMANG",
 "任意星耀图纸":"E_LOOP_TASK_TYPE_ANY_GREEN_XINGYAO",
 "对话":"E_LOOP_TASK_TYPE_DIALOG",
 "日常":"E_LOOP_TASK_REWARD_TYPE_DAILY",
 "周常":"E_LOOP_TASK_REWARD_TYPE_WEEKLY",
 "天族":"E_SPECIES_TIANZU",
 "圣族":"E_SPECIES_SHENGZU",
 "精灵":"E_SPECIES_JINGLING",
 "降级":"E_TRAIN_MATE_FAILED_PUNISHMENT_DEGRADE",
 "消失":"E_TRAIN_MATE_FAILED_PUNISHMENT_DISMISS",
 "清零":"E_TRAIN_MATE_FAILED_PUNISHMENT_CLEARLEVEL",
 "安全级":"E_TRAIN_MATE_FAILED_PUNISHMENT_SAFELEVEL",
 "财神":"E_NEW_SERVER_PRIZE_CAISHEN",
 "新服充值":"E_NEW_SERVER_PRIZE_RECHARGE_RMB",
 "付费开启":"E_CONSUME_OPEN",
 "新服等级":"E_NEW_SERVER_PRIZE_LEVEL",
 "新服实力排行":"E_NEW_SERVER_PRIZE_BATTLE_POWER",
 "新服球星排行":"E_NEW_SERVER_PRIZE_MATE",
 "新服奖杯排行":"E_NEW_SERVER_PRIZE_CUPNUMBER",
 "新服等级排行":"E_NEW_SERVER_PRIZE_LEVELRANK",
 "每日":"ONLINE_PACKET_DAILY",
 "单次":"ONLINE_PACKET_ONCE",
 "账号认证":"E_BUSINESS_PASSPORT_AUTHENTICATION",
 "管理控制":"E_BUSINESS_MASTER_CONTROL",
 "业务主机":"E_BUSINESS_DEPLOYMENT_MASTER",
 "业务从机":"E_BUSINESS_DEPLOYMENT_SLAVE",
 "集合业务":"E_BUSINESS_DPLOYMENT_SINGLETON",
 "生命类":"E_WUSOULTYPE_HP",
 "怒气类":"E_WUSOULTYPE_ANGER",
 "物理攻击类":"E_WUSOULTYPE_PHYATTACK",
 "魔法攻击类":"E_WUSOULTYPE_MAGICATTACK",
 "物理防御类":"E_WUSOULTYPE_PHYDEFENSE",
 "魔法防御类":"E_WUSOULTYPE_MAGICDEFENSE",
 "命中等级类":"E_WUSOULTYPE_ACCURATELEVEL",
  "见习勇士":"E_NOBILITY_JIANXIYONGSHI",
 "勇士":"E_NOBILITY_YONGSHI",
 "见习士兵":"E_NOBILITY_JIANXISHIBING",
 "士兵":"E_NOBILITY_SHIBING",
 "见习中尉":"E_NOBILITY_JIANXIZHONGWEI",
 "中尉":"E_NOBILITY_ZHONGWEI",
 "骑尉":"E_NOBILITY_QIWEI",
 "都尉":"E_NOBILITY_DUWEI",
 "勋爵":"E_NOBILITY_XUNJUE",
 "男爵":"E_NOBILITY_NANJUE",
 "子爵":"E_NOBILITY_ZIJUE",
 "伯爵":"E_NOBILITY_BOJUE",
 "侯爵":"E_NOBILITY_HOUJUE",
 "公爵":"E_NOBILITY_GONGJUE",
 "王爵":"E_NOBILITY_WANGJUE",
 "限定万魔塔":"E_RANKAWARDTYPE_LIMIT",
 "无限万魔塔":"E_RANKAWARDTYPE_UNLIMIT",
 "神佑":"E_PASSIVESKILL_GODSPEED",
 "连击":"E_PASSIVESKILL_DOUBLEHIT",
 "反震":"E_PASSIVESKILL_ANTIINJURY",
 "合击":"E_PASSIVESKILL_ASISTATTACK",
 "反击":"E_PASSIVESKILL_COUNTERATTACK",  
 "韧性值":"E_PASSIVESKILL_TENACITY",
 "暴击伤害":"E_PASSIVESKILL_CRITHURT",
 "物理伤害结果":"E_PASSIVESKILL_NORMALHURT",
 "生命上限":"E_PASSIVESKILL_HPLOWERLIMIT",
 "当前生命":"E_PASSIVESKILL_HPCURRENT",
 "反震伤害":"E_PASSIVESKILL_ANTIINJURYHURT",
 "触发概率":"E_PASSIVESKILL_TRIGGERCHANCE",
 "增加值":"E_TYPEOPERATE_ADDNUMBER",
 "等级增加值":"E_TYPEOPERATE_ADDLEVELNUMBER",
 "结果百分比":"E_TYPEOPERATE_RESULTPERSENT",
 "增加百分比":"E_TYPEOPERATE_ADDPERCENT",
 "减少百分比":"E_TYPEOPERATE_SUBPERCENT",
  "增加数值":"E_TYPEOPERATE_ADD_NUMERIC",
 "减少数值":"E_TYPEOPERATE_DEC_NUMERIC",
 "死亡时":"E_TRIGGERTIME_DEAD",
 "普攻时":"E_TRIGGERTIME_NORMALATTACK",
 "受近战普攻时":"E_TRIGGERTIME_BE_NEARNORMALATTACK",
 "受普攻时":"E_TRIGGERTIME_BE_NORMALATTACK",
 "开战前":"E_TRIGGERTIME_PREFIGHT",
 "技能已触发":"E_TRIGGERTIME_SKILLDONE",
 "合击选择时":"E_TRIGGERTIME_TOGETHERATTACK",
 "法术攻击时":"E_TRIGGERTIME_MAGICATTACK",
 "物理攻击时":"E_TRIGGERTIME_PHYATTACK",
 "被克制":"E_TRIGGERTIME_RESTRAINED",
 "系统公告":"E_SYSTEM_BROADCAST",
 "滚动条公告":"E_SCROLLBAR_BROADCAST",
 "光":"E_ELEMENTTYPE_RAY",
 "暗":"E_ELEMENTTYPE_DARK",
 "地":"E_ELEMENTTYPE_THEEARTH",
 "水":"E_ELEMENTTYPE_WATER",
 "火":"E_ELEMENTTYPE_FIRE",
 "风":"E_ELEMENTTYPE_WIND",
 "无":"E_WU",
 "白名":"E_WHITENAME",
 "红名":"E_REDNAME",
 "黑名":"E_BLACKNAME",
 "物法攻击":"E_PHYMAGIC",
 "每日活动":"E_OPERATE_DAILY",
 "每周活动":"E_OPERATE_WEEKLY",
 "每月活动":"E_OPERATE_MONTHLY",
 "结拜返利":"E_BROTHERS_BOON",
 "结拜充值":"E_BROTHERS_RECHARGE",
 "帮派日常":"E_GANG_DAILY",
 "帮派建设":"E_GANG_CONSTRUCT",
 "礼包":"E_OPERATE_LIBAO",
 "单次活动":"E_OPERATE_SINGLE",
 "充值限量":"E_OPERATE_IAP_LIMITED",
 "活动充值送球员":"E_OPERATE_CHONGZHI_MATE",
 "活动充值送灵翅":"E_OPERATE_CHONGZHI_WING",
 "新活动充值送球员":"E_OPERATE_CHONGZHI_MATE_NEW",
 "新活动充值送灵翅":"E_OPERATE_CHONGZHI_WING_NEW",
 "充值送礼":"E_OPERATE_RECHAREGE_GETPRIZE",
 "刷新碎片":"E_OPERATE_REFRESH_GET_FRAGMENT",
 "活动球员":"E_OPERATE_REFRESH_APPEAR_MATE",
 "订单回调服务":"E_BUSINESS_ORDER",
 "消费限量":"E_OPERATE_IAP_XIAOFEI",
 "B金币":"E_OBJ_BMONEY",
 "B钻石":"E_OBJ_BDIAMOND",
 "B物品":"E_OBJ_BITEM",
 "B球员":"E_OBJ_BMATE",
 "门将（左）":"E_FOOTBALL_MENJIANG_LEFT",
 "后卫一（左）":"E_FOOTBALL_HOUWEI_1_LEFT",
 "后卫二（左）":"E_FOOTBALL_HOUWEI_2_LEFT",
 "后卫三（左）":"E_FOOTBALL_HOUWEI_3_LEFT",
 "中场一（左）":"E_FOOTBALL_ZHONGCHANG_1_LEFT",
 "中场二（左）":"E_FOOTBALL_ZHONGCHANG_2_LEFT",
 "中场三（左）":"E_FOOTBALL_ZHONGCHANG_3_LEFT",
 "中场四（左）":"E_FOOTBALL_ZHONGCHANG_4_LEFT",
 "前场一（左）":"E_FOOTBALL_QIANCHANG_1_LEFT",
 "前场二（左）":"E_FOOTBALL_QIANCHANG_2_LEFT",
 "前场三（左）":"E_FOOTBALL_QIANCHANG_3_LEFT",
 "开球一（左）":"E_FOOTBALL_KAIQIU_1_LEFT",
 "开球二（左）":"E_FOOTBALL_KAIQIU_2_LEFT",
 "门将（右）":"E_FOOTBALL_MENJIANG_RIGHT",
 "后卫一（右）":"E_FOOTBALL_HOUWEI_1_RIGHT",
 "后卫二（右）":"E_FOOTBALL_HOUWEI_2_RIGHT",
 "后卫三（右）":"E_FOOTBALL_HOUWEI_3_RIGHT",
 "中场一（右）":"E_FOOTBALL_ZHONGCHANG_1_RIGHT",
 "中场二（右）":"E_FOOTBALL_ZHONGCHANG_2_RIGHT",
 "中场三（右）":"E_FOOTBALL_ZHONGCHANG_3_RIGHT",
 "中场四（右）":"E_FOOTBALL_ZHONGCHANG_4_RIGHT",
 "前场一（右）":"E_FOOTBALL_QIANCHANG_1_RIGHT",
 "前场二（右）":"E_FOOTBALL_QIANCHANG_2_RIGHT",
 "前场三（右）":"E_FOOTBALL_QIANCHANG_3_RIGHT",
 "开球一（右）":"E_FOOTBALL_KAIQIU_1_RIGHT",
 "开球二（右）":"E_FOOTBALL_KAIQIU_2_RIGHT",
 "不失球获得胜利":"E_FBCONDITION_NEVERLOSE_WIN",
 "限定球员数量取胜":"E_FBCONDITION_LIMITPLAYER",
 "单人单场进多球":"E_FBCONDITION_SINGLEPERSON_GOALIN",
 "限定分差取胜":"E_FBCONDITION_LIMITDISTANCETOTAL",
 "限定进球取胜":"E_FBCONDITION_LIMITGOALIN_WIN",
 "按时间随机触发":"E_FOOTBALL_SKILL_TRIGGER_RANDOM",
 "射门时触发":"E_FOOTBALL_SKILL_TRIGGER_SHOOT",
 "守门时触发":"E_FOOTBALL_SKILL_TRIGGER_KEEP",
 "传球时触发":"E_FOOTBALL_SKILL_TRIGGER_PASS_BALL",
 "过人时触发":"E_FOOTBALL_SKILL_TRIGGER_PASS_PLAYER",
 "带球时触发":"E_FOOTBALL_SKILL_TRIGGER_WITH_BALL",
 "防守时触发":"E_FOOTBALL_SKILL_TRIGGER_DEFENCE",
 "加状态":"E_FOOTBALL_SKILL_EFFECT_ADD_BUF",
 "时间暂停":"E_FOOTBALL_SKILL_EFFECT_CEASE_TIME",
 "吊射":"E_FOOTBALL_SKILL_EFFECT_LONG_SHOOT",
 "传球":"E_FOOTBALL_SKILL_EFFECT_PASS",
 "己方全体":"E_FOOTBALL_SKILL_TARGET_SELF_TEAM",
 "对方全体":"E_FOOTBALL_SKILL_TARGET_ENEMY_TEAM",
 "足球自己":"E_FOOTBALL_SKILL_TARGET_SELF",
 "当前带球人":"E_FOOTBALL_SKILL_TARGET_MAN_WITH_BALL",
 "己方门将":"E_FOOTBALL_SKILL_TARGET_SELF_KEEPER",
 "对方门将":"E_FOOTBALL_SKILL_TARGET_ENEMY_KEEPER",
 "足球全体":"E_FOOTBALL_SKILL_TARGET_ALL",
 "周围敌人":"E_FOOTBALL_SKILL_TARGET_AROUND",
 "射门":"E_FOOTBALL_SKILL_ATTR_SHOOT",
 "平衡":"E_FOOTBALL_SKILL_ATTR_BALANCE",
 "控球":"E_FOOTBALL_SKILL_ATTR_CONTROL",
 "技能属性传球":"E_FOOTBALL_SKILL_ATTR_PASS",
 "干扰":"E_FOOTBALL_SKILL_ATTR_OBSTRUCT",
 "侵犯":"E_FOOTBALL_SKILL_ATTR_CONCEDE",
 "抢断":"E_FOOTBALL_SKILL_ATTR_STEAL",
 "拦截":"E_FOOTBALL_SKILL_ATTR_INTERCEPT",
 "扑救":"E_FOOTBALL_SKILL_ATTR_SAVE",
 "手控球":"E_FOOTBALL_SKILL_ATTR_HANDBALL",
 "速度":"E_FOOTBALL_SKILL_ATTR_SPEED",
 "体力伤害":"E_FOOTBALL_SKILL_ATTR_HP_HURT",
 "进攻":"E_FOOTBALL_SKILL_ATTR_ATTACK",
 "防守":"E_FOOTBALL_SKILL_ATTR_DEFENCE",
 "守门":"E_FOOTBALL_SKILL_ATTR_KEEP",
 "昏迷":"E_FOOTBALL_SKILL_ATTR_COMA",
 "足球混乱":"E_FOOTBALL_SKILL_ATTR_CONFUSE",
 "数值类型":"E_FOOTBALL_TASK_ARGTYPE_NUMBER",
 "数值枚举类型":"E_FOOTBALL_TASK_ARGTYPE_COUNTENUM",
 "普通联赛":"E_FOOTBALL_GAMETYPE_NORMAL",
 "巨星对决":"E_FOOTBALL_GAMETYPE_SUPPERSTAR",
 "指定比赛获胜":"E_FOOTBALL_TASKTYPE_SPECIFYGAMEWIN",
 "任意球员训练次数":"E_FOOTBALL_TASKTYPE_PLAYERTRAINNUMBER",
 "任意球员升级次数":"E_FOOTBALL_TASKTYPE_PLAYERLEVELUPNUMBER",
 "获得奖杯":"E_FOOTBALL_TASKTYPE_GETCUPNUMBER",
 "指定类型比赛":"E_FOOTBALL_TASKTYPE_SPECIFYGAMETYPE",
 "进球数":"E_FOOTBALL_TASKTYPE_GOALINNUMBER",
 "球员实力达到指定值":"E_FOOTBALL_TASKTYPE_PLAYERPOWERTONUMBER",
 "获得指定品质球员":"E_FOOTBALL_TASKTYPE_GETSPECIFYQUALITYPLAYER",
 "相等":"E_FOOTBALL_TASKARG_COMPUTETYPE_EQUAL",
 "大于或等于":"E_FOOTBALL_TASKARG_COMPUTETYPE_LARGER",
 "球员":"E_FOOTBALL_OBJECTTYPE_MATE",
 "道具":"E_FOOTBALL_OBJECTTYPE_ITEM",
 "前场":"E_FOOTBALL_STRIKERFIELD",
 "中场":"E_FOOTBALL_MIDFIELD",
 "后场":"E_FOOTBALL_BACKFIELD",
 "门将":"E_FOOTBALL_KEEPER",
 "充值排行":"E_OBJ_RANKOFRECHARGE_TYPE",

                "鼓励":"E_EMOTION_ENCOURAGE=20010001",
                "安抚":"E_EMOTION_EASE",
                "赞美":"E_EMOTION_PRAISE",
                "告白":"E_EMOTION_LOVE_ANNOUNCEMENT",
                "逃避":"E_EMOTION_LEAVE",
                "吐槽":"E_EMOTION_BERATE",
                "挑逗":"E_EMOTION_SUCK",
                "同意":"E_EMOTION_AFFIRMATIVE",
                "否认":"E_EMOTION_NEGATIVE",
                "贿赂":"E_EMOTION_BRIBE",
                "搭讪":"E_EMOTION_ACCOST",
                "追问":"E_EMOTION_ASK",
                "倾诉":"E_WORDSPOOL_SHARE_FEELING",
                
                "时事":"E_WORDSPOOL_CURRENT_AFFAIR=20020001",
                "美食":"E_WORDSPOOL_FOOD",
                "故事模式":"E_WORDSPOOL_STORY",
                "屌丝":"E_TITLE_DIAOSI",
                
                "食堂":"E_SCENE_DINNINGROOM=20030001",
                "操场":"E_SCENE_PLAYGROUND",
                "教室":"E_SCENE_CLASSROOM",
                "大门":"E_SCENE_GATE",

                "好感度":"E_PRIZE_FAVOR=20040001",
                "货物":"E_PRIZE_GOODS",
                "触发对话":"E_PRIZE_TRIGGER_WORDS",

                "一号女主":"E_NPC_NAME_EPSILON=20050001",
                "二号女主":"E_NPC_NAME_HARU2",
                "三号女主":"E_NPC_NAME_HARU",
                "小橙":"E_NPC_NAME_CHENG",
                "柿子":"E_NPC_NAME_SHI",
                "所有人":"E_NPC_NAME_SUOYOUREN",
                
                                #动作
                "待机":"E_MOTION_IDLE=20060001",
                "点头":"E_MOTION_NOD",
                "摇头":"E_MOTION_DENY",
                "偏头":"E_MOTION_INCLINE",
                "喜悦":"E_MOTION_DELIGHTED",
                "生气":"E_MOTION_ANGRY",
                "不高兴":"E_MOTION_SAD",
                "吃惊":"E_MOTION_SURPRISED",
                "失望":"E_MOTION_DISAPPOINTED",
                "满足":"E_MOTION_SATISFACTORY",
                "大吃惊":"E_MOTION_OOPS",
                "我想回家":"E_MOTION_GO_HOME",
                "大生气":"E_MOTION_NOT_GOOD",
                "败给你了":"E_MOTION_TURN_ME_OFF",
                "摇晃":"E_MOTION_SHAKE",
                "talk_nv1":"E_MOTION_TALK_NV1",
                "talk_nv10":"E_MOTION_TALK_NV10",
                "talk_nv12":"E_MOTION_TALK_NV12",
                "talk_nv3":"E_MOTION_TALK_NV3",
                "talk_nv5":"E_MOTION_TALK_NV5",
                "talk_nv8":"E_MOTION_TALK_NV8",

#                "是":"E_YES_YES=20070001",
#                "否":"E_NO_NO",

                #道具
                "红色被子":"E_ITEM_RED_QUILT=20080001",
                "iPhone5":"E_ITEM_IPHONE_5",
                "康熙字典":"E_ITEM_KANGXI_DICTIONARY",
                "百元":"E_ITEM_HUNDRED_MONEY",
                "康师傅红烧牛肉面":"E_ITEM_KANGSHIFU_HONGSHAONIUROUMIAN",
                
                #谈话索引
                "收到礼物":"E_MUSIC_SHOUDAOLIWU=20090001",
                "唉":"E_MUSIC_AI",
                "妈妈礼物":"E_MUSIC_MAMALIWU",
                "你想什么":"E_MUSIC_NIXIANGSHENME",
                "爸爸送书":"E_MUSIC_BABASONGSHU",
                "满头雾水":"E_MUSIC_MANTOUWUSHUI",



}


import string

def fun_build_map_assign(chinese):
    s = chinese.encode('utf8')
    s2 = """%r"""%(s)
    s2 = s2[1:-1]
    global g_enum_define
    l = string.split(g_enum_define[chinese], "=")
    enum = l[0]
    num = None
    if len(l) > 1:
        num = l[1]
    #print enum , num
    return """    mp["%(s2)s"] = %(enum)s;//%(chinese)s """%(locals())

def fun_build_map_assign_string(chinese):
    s = chinese.encode('utf8')
    s2 = """%r"""%(s)
    s2 = s2[1:-1]
    global g_enum_define
    l = string.split(g_enum_define[chinese], "=")
    enum = l[0]
    num = ""
    if len(l) > 1:
        num = "=" + l[1]

    return """    mp[%(enum)s] = "%(s2)s";//%(chinese)s """%(locals())


def fun_build_enum(chinese):
    #s = chinese.encode('utf8')
    #s2 = """%r"""%(s)
    #s2 = s2[1:-1]
    global g_enum_define
    enum = ""
    num = ""
    try:
        l = string.split(g_enum_define[chinese], "=")
        enum = l[0]
        num = ""
        if len(l) > 1:
            num = "=" + l[1]

    except Exception:
        print chinese;
    #print "chinese is  --",chinese, "--"
    #chinese = chinese.encode("gbk")
    return """    %(enum)s%(num)s,//%(chinese)s """%(locals())

def main():
    global g_enum_define
    h_file_template = """#ifndef __CONFIGURE_ENUM_MAP_H__
#define __CONFIGURE_ENUM_MAP_H__
#include <string>
#include <map>
using namespace std;


enum EConfigure
{
    E_CONFIGURE_NONE,
%(enums)s

};

int getEnumValue(string name);
const char* getEnumString(int value);
void initEnumMap();
void initEnumStringMap();
#endif
"""

    w = open('../Common/Configure/ConfigureEnumMap.h', 'w')
    enums = string.join(map(fun_build_enum, g_chinese_l), '\n')
    s2 = h_file_template%(locals())
    #s2 = s2.encode("gbk")
    w.write(s2)
    w.close()
    
    w = open('../Common/Configure_server/ConfigureEnumMap.h', 'w')
    enums = string.join(map(fun_build_enum, g_chinese_l), '\n')
    s2 = h_file_template%(locals())
    #s2 = s2.encode("gbk")
    w.write(s2)
    w.close()
    
    cpp_file_template = """#include "ConfigureEnumMap.h"
typedef map<string, int> CONFIGUREENUMMAP;
CONFIGUREENUMMAP    g_mpConfigureEnum;

typedef map<int, string> CONFIGUREENUMMAP_STRING_KEY;
CONFIGUREENUMMAP_STRING_KEY g_mpConfigureEnumString;

void initEnumMap()
{
    CONFIGUREENUMMAP& mp = g_mpConfigureEnum;
%(mapassign)s
}

void initEnumStringMap()
{
    CONFIGUREENUMMAP_STRING_KEY& mp = g_mpConfigureEnumString;
%(mapassignString)s
}

int getEnumValue(string name)
{
    CONFIGUREENUMMAP::iterator iter = g_mpConfigureEnum.find(name);
    if (iter != g_mpConfigureEnum.end())
    {
        return iter->second;
    }
    if (name != "")
    {
        int anchor = 0;
    }
    return E_CONFIGURE_NONE;
}

const char* getEnumString(int value)
{
    CONFIGUREENUMMAP_STRING_KEY::iterator iter = g_mpConfigureEnumString.find(value);
    if (iter != g_mpConfigureEnumString.end())
    {
        return iter->second.c_str();
    }
    return "";
}
"""
    w = open('../Common/Configure/ConfigureEnumMap.cpp', 'w')
    mapassign = string.join(map(fun_build_map_assign, g_chinese_l), '\n')
    mapassignString = string.join(map(fun_build_map_assign_string, g_chinese_l), '\n')
    s = cpp_file_template%(locals())
    s = s.encode("gbk")
    w.write(s)
    w.close()
    
    w = open('../Common/Configure_server/ConfigureEnumMap.cpp', 'w')
    mapassign = string.join(map(fun_build_map_assign, g_chinese_l), '\n')
    mapassignString = string.join(map(fun_build_map_assign_string, g_chinese_l), '\n')
    s = cpp_file_template%(locals())
    s = s.encode("gbk")
    w.write(s)
    w.close()

main()
print "OK"
