# -*- coding: utf8 -*-
import string
g_msg_define={
                            "您招募%s%s#FFFFFF成功":"NIN_ZHAOMU_CHENGGONG",
              "金币不足":"JINQIAN_BUZU",
              "体力不足":"TILI_BUZU",
              "等级不足":"DENGJI_BUZU",
              "条件不足":"TIAOJAIN_BUZU",
              "球员不存在":"YONGBING_BUCUNZAI",
              "领导力不足":"LINGDAOLI_BUZU",
              "物品不足":"WUPIN_BUZU",
              "钻石不足":"ZUANSHI_BUZU",
              "材料不足":"CAILIAO_BUZU",
              "进化所需要的球员不存在":"JINHUA_YONGBING_CAILIAO_BUZU",
              "该球员无法进化":"YONGBING_WUFA_JINHUA",
              "您不可雇佣该球员":"BUKE_GUYONG",
              "该球员已被其他玩家雇佣！":"ALREADY_HIRED",
              "欢迎加入官方QQ群讨论问题！官方QQ群号：%d":"HUANYING_JIARU_QQ_QUN",
              
              "您的球员队伍已经满了,需要你解雇一个":"GUYONG_DUIWU_MANLE",
              "#FFFF00%s#FFFFFF成功招募#A001FC%s#FFFFFF，球员队伍实力大增":"CHENGGONG_GUYONG",
              "#FFFF00%s#FFFFFF在公共酒馆成功招募了#A001FC%s#FFFFFF，球员队伍实力大增":"CHENGGONG_GUYONG_PUBLIC",
              "#FFFF00%s#FFFFFF招募了#A001FC%s#FFFFFF":"CHENGGONG_GUYONG_GLOBAL",
              "您消耗了%d钻石":"XIAOHAO_ZUANSHI",
              "您消耗了%d金币":"XIAOHAO_JINBI",
              "您消耗了%d奖杯":"XIAOHAO_SHENGWANG",
              "您消耗了%d体力":"XIAOHAO_TILI",
              "又有一批实力强悍的球员到来,赶快去招募吧":"SHUAXIN_ZHAOMU_GUANGBO",
              "发现天赋秉异,英气逼人的稀有球员!":"GAOJI_YONGBING_TISHI",
              "装备强化等级不能超过主角等级":"QIANGHUA_DENGJI_DI",
              "您已经是vip了":"ALREADY_VIP",
              "目前装备强化不需要冷却时间":"WU_QIANGHUA_SHIJIAN",
              "装备强化还在冷却中":"QIANGHUA_LENGQUE_ZHONG",
              "#FF0000强化失败":"QIANGHUA_SHIBAI",
              "#FF0000加星失败":"JIAXING_SHIBAI",
              "#FF0000您已经拥有该vip功能":"YIJING_YONGYOU_VIP",
              "恭喜您开通了vip功能":"GONGXI_KAITONG_VIP",
              "激活成功,消耗%d钻石":"JIHUO_CHENGGONG",
              "激活失败,消耗%d钻石":"JIHUO_SHIBAI",
              "合成成功":"HECHENG_CHENGGONG",
              "%s历尽千辛万苦，成功集齐了%s%s":"SHOUJI_CHIBANG_TAOZHUANG_CHENGGONG",
              "%s成功激活了%s%s":"JIHUO_CHIBANG_CHENGGONG",
              "#ffffff":"BAI",
              "#00d03c":"LV",
              "#036cfb":"LAN",
              "#a001fc":"ZI",
              "#ec0312":"HONG",
              "#fbc700":"JIN",
              "#FF0000":"HUANG",
              "该精英副本需要重置才可在此进入":"XUYAO_CHONGZHI_JINGYING_FUBEN",
              "该物品%d找不到导航信息!":"WUPIN_DAOHANG_BUCUNZAI",
              "您接受了任务: %s!":"JIESHOU_RENWU",
              "您完成了任务: %s!":"WANCHENG_RENWU",
              "%s:%d/%d":"RENWU_GUAIWU_TISHI",
              "%s:%d/%d ":"RENWU_WUPIN_TISHI",
              "您的包裹空间不够!": "BAOGUO_KONGJIAN_BUGOU",
              "您的球员队伍空位不足!": "HUOBAN_YIMAN",
              "您的领导力不足,尚缺%d!": "LINGDAOKI_BUZU",
              "您的包裹已经满了,请留出空格以后再进入副本!": "BAOGUO_MAN_FUBENJINZHI",
              "请准备至少三个空格,不然可能无法获得掉落物品!": "BAOGUO_MAN_FUBEN_GAOJING",
              "球员栏已满，请解雇一些劣质的球员。": "HUOBAN_MAN_FUBENJINZHI",
              "球员栏还剩一个空位，请及时解雇劣质的球员。": "HUOBAN_MAN_FUBEN_GAOJING",
              "充值大优惠，童叟无欺，欢迎惠顾！":"SHANGDIAN_GONGGAO",
              "没有可以领取的奖励": "ZHAOBUDAO_JIANGLI",
              "请清空包裹再领奖!": "QINGKONG_BAOGUO_JIANGLI",
              "奖励记录已经满了,无法领取":"JIANGLI_JILU_MANLE",
              "领取奖励失败":"LINGQU_JIANGLI_SHIBAI",
              "您尚未开启该副本!":"BUNENG_JINRU_FUBEN",
              "阵型中同一个球员出现二次！":"ZHENXING_HUOBAN_CHONGFU",
              "请留出足够的空位来领取任务奖励":"RENWUJIANGLI_KONGWEI_BUZU",
              "达到%d级才能使用此道具":"SHIYONGDAOJU_DENGJI_TISHI",
              "翅魂全都达到%d阶以上时，才能领取激活%d阶奖励":"SHENGJI_CHI_BANG_SHIBAI_DENGJIBUZU",
              "你的翅魂等级均在%d阶以上，无需再次激活":"SHENGJI_CHI_BANG_SHIBAI_DENGJICHAOGUO",
              "球员已达当前品质最高级，品质越高的球员等级上限越高。":"YONGBING_WUFA_CHIDONGXI_DENGJIZUIGAO",
              "获得金币%d":"JIANGLI_JINBI",
              "获得奖杯&d":"JIANGLI_SHENGWANG",
              "获得物品%s%s#FFFFFF%d个":"JIANGLI_WUPIN",
              "获得装备%s%s#FFFFFF%d个":"JIANGLI_ZHUANGBEI",
              "获得经验%d":"JIANGLI_JINGYAN",
              "获得钻石%d":"JIANGLI_ZUANSHI",
              "获得球员%s%d个":"JIANGLI_YONGBING",
              "当前%s%s#ffffff不足，集齐%d个才能兑换":"SUIPIAN_BUZU",
              "无法获得奖品":"WUFA_HUODE_JIANGPIN",
              "该任务无法完成":"MISSION_CAN_NOT_BE_FINISHED",
              "该物品无法使用":"WUPIN_WUFA_SHIYONG",
              "努力强化装备、升级球员提高实力吧！（当前怪物闪避等级为%d，优先强化手套提高命中等级，避免出现全Miss的情况）":"ZHANDOU_SHIBAI_TISHI",
              "#FFFF00%s（可接）#FFFFFF":"KEJIE_RENWU",
              "#C0C0C0%s（未完成）#FFFFFF":"WEIWANCHENG_RENWU",
              "#00FF00%s（可交付）#FFFFFF":"YIWANCHENG_RENWU",
              "您的阵型中没有配置伙伴，请在阵型中配置出战的伙伴再来挑战吧！": "ZHENXING_KONG",
              "该副本无法战斗":"WU_GUAIWU_ZHENXING",
              "服务器%d秒后即将关闭，进行更新，请及时下线以免数据丢失":"FUWUQI_GUANBI_DAOJISHI",
              "该物品不可出售":"BUKE_DIUQI",
              "服务器人数已满，请稍后再尝试登录该服。":"FUWUQI_YIMAN",
              "包裹已经全部解锁":"BAOGUO_QUANBU_JIESUO",
              "副本配置错误":"FUBEN_PEIZHI_CUOWU",
              "格子还没解锁":"GEZI_HAIMEI_JIESUO",
              "没有可交换的物品或者装备":"MEIYOU_KE_JIAOHUAN_WUPIN",
              "该位置只能放装备":"ZHINENG_ZHUANGBEI",
              "该位置只能放置武魂":"ZHINENG_ZHUANGBEIWUHUN",
              "找不到目标球员":"ZHAOBUDAO_MUBIAO_YONGBING",
              "找不到目标物品":"ZHAOBUDAO_MUBIAO_WUPIN",
              "不可合成":"BUKE_HECHENG",
              "装备配置错误":"ZHUANGBEI_PEIZHI_CUOWU",
              "物品配置错误":"WUPIN_PEIZHI_CUOWU",
              "球员等级不符，无法使用此装备":"YONGBING_DENGJI_DI_ZHUANGBEI_BUNENG",
              "球员职业不符，无法使用此装备":"YONGBING_ZHIYE_BUFU_ZHUANGBEI_BUNENG",
              "":"WU_CUOWU",
              "充值成功!恭喜您获得%d钻石":"CHONGZHI_CHENGGONG",
              "充值失败!":"CHONGZHI_SHIBAI",
              "该物品不可使用!":"WUPIN_BUKE_SHIYONG",#dragonsword
              "欢迎关注新浪微博":"DENGLU_GONGGAO_3",
              "@@龙剑%s":"DENGLU_GONGGAO_4",
              "欢迎加入扣扣群%d反馈问题。":"DENGLU_GONGGAO_1",
              "感谢大家玩我们游戏，即将发布新版本修复大量错误，届时需到苹果官网下载客户端，已注册的玩家，更新后都会获得%d钻石奖励！":"DENGLU_GONGGAO_2",
              "主人，很高兴您来到龙剑的世界哟~我是传音小精灵喵儿，":   "DENGLU_LINSHI_GONGGAO_1",
              "偷偷告诉你，我们即将发布新版本对游戏进行大幅优化了哟，": "DENGLU_LINSHI_GONGGAO_2",
              "主人可以到苹果官网下载最新的客户端，":              "DENGLU_LINSHI_GONGGAO_3",
              "更新后都会获得%d钻石奖励！":                     "DENGLU_LINSHI_GONGGAO_4",
              "让我们一起去新的龙剑世界中并肩作战吧！喵~~":         "DENGLU_LINSHI_GONGGAO_5",
              "主人，很高兴您来到龙剑世界，我们即将发布新版本对游戏大幅优化。":"DENGLU_LINSHI_GONGGAO_6",
              "届时需到#00FF00%s#FFFFFF下载更新。":"DENGLU_LINSHI_GONGGAO_7",
              "更新后已注册玩家将获得#00FF00%d钻石#FFFFFF奖励！欢迎关注新浪微博@@龙剑%s。":"DENGLU_LINSHI_GONGGAO_8",
              "欢迎来到易元足球世界，祝您游戏愉快!欢迎加入官方#00d03cQQ群%d":"DENGLU_LINSHI_GONGGAO_9",
              "该环任务不需要花钻石":"HUAN_RENWU_BU_XUYAO_ZUANSHI",
              "灵翅残影的魂力正在消散……":"TISHI_CHIBANG_XIAOSHI_1",
              "#00FF00充值任意金额#FFFFFF即可立刻#00FF00永久激活灵翅#FFFFFF！":"TISHI_CHIBANG_XIAOSHI_2",
              "天降洪福！%s开启%s获得了%s%d个":"LIBAO_KAIQI_TISHI_WUPIN",
              "财源滚滚！%s开启%s获得了%s%d金币":"LIBAO_KAIQI_TISHI_JINBI",
              "财源滚滚！%s开启%s获得了%s%d钻石":"LIBAO_KAIQI_TISHI_ZUANSHI",
              "#FFFFFF天降洪福!#00FF00%s#FFFFFF开启%s#FFFFFF获得了%s#00FF00%d#FFFFFF个":"SCROLLBAR_TISHI_WUPIN",
              "#FFFFFF财源滚滚！#00FF00%s#FFFFFF开启%s#FFFFFF获得了%s#00ff00%d#FFFFFF金币":"SCROLLBAR_TISHI_GOLD",
              "#FFFFFF财源滚滚！#00FF00%s#FFFFFF开启%s#FFFFFF获得了%s#00FF00%d#FFFFFF钻石":"SCROLLBAR_TISHI_DIAMOND",
              "#00FF00%s#FFFFFF训练【%s#FFFFFF】+#00FF00%d#FFFFFF成功":"SCROLLBAR_TISHI_TRIAL",
              "#FFFFFF恭喜玩家 #00FF00%s#FFFFFF的【%s#FFFFFF】球员进化到#00FF00%d#FFFFFF星球员，球员队伍实力大增！":"SCROLLBAR_TISHI_JINHUA",
              "#00FF00%s#FFFFFF在竞技场中无人能挡，已连胜#00FF00%d#FFFFFF场！":"SCROLLBAR_TISHI_ZHUZAI_20",
              "#FFFFFF恭喜玩家#00FF00%s#FFFFFF荣升%s%s#FFFFFF爵位，指挥球员能力大幅提升！":"SCROLLBAR_TISHI_JUEWEI_LEVELUP",
              "#00FF00%s#FFFFFF在竞技中不幸跌出前#00FF00%d#FFFFFF名，失去了%s%s#FFFFFF爵位......":"SCROLLBAR_TISHI_JUEWEI_LEVELDOWN",
              "#FFFFFF玩家#00FF00%s#FFFFFF合成出%s#FFFFFF获得新形象！":"SCROLLBAR_TISHI_WINGLEVELUP",
              "#FFFFFF恭喜玩家#00FF00%s#FFFFFF合成出%s#FFFFFF，球员属性大幅提升！":"SCROLLBAR_TISHI_COMPOUNDEQUIP",
              "#FFFFFF霸气外露，#00FF00%s#FFFFFF获赠限量绝版灵翅%s#FFFFFF，全队球员属性大幅提升！":"SCROLLBAR_TISHI_COMPOUNDEQUIP_WANGZHE",
              "#FFFFFF惊呆小伙伴，#00FF00%s#FFFFFF合成出全服限量灵翅%s#FFFFFF，全队球员实力大增！":"SCROLLBAR_TISHI_COMPOUNDEQUIP_SHENGLING",
              "#FFFFFF先充先得，#00FF00%s#FFFFFF抢先获得全服限量神球员%s#FFFFFF%d个":"SCROLLBAR_TISHI_COMPOUNDEQUIP_MATE",
              "财源滚滚！%s连续%d天圆满完成日常连环，获得%d倍奖励#00FF00%d#FFFFFF金币！":"SHIBEI_RIHUAN_DAJIANG",
              "财源滚滚！%s连续%d周圆满完成国家连环，获得%d倍奖励#00FF00%d#FFFFFF金币！":"SHIBEI_ZHOUHUAN_DAJIANG",
              "%s品质的装备最高只能强化到%d级。":"QIANGHUA_DENGJI_XIANZHI",
              "该球员升级到%d级才可以进化。":"YONGBING_JINHUA_XIANZHI",              
              "排行榜上暂无记录。":"PAIHANGBANG_WUJILU",              
              "部位不正确":"BUWEI_BUZHENGQUE",
              "购买成功！获得金币%d":"GOUMAI_JINBI_CHENGONG",              
              "对方的排名发生了变化，只能挑战比自己排名高的玩家":"JINGJICHANG_PAIMING_CUOWU",     
              "城主凯尔":"CHENGZHU_KAIER",
              "魔族将领":"MOZU_JIANGLING",
              "#00FF00%s#FFFFFF现身热血之城，大家赶快去挑战他们吧！":"TIANJIANG_CREATE_DYNAMICNPC",
              "身上有刚缉拿的#00FF00%s#FFFFFF的气味，无法再次靠近（%d秒后气味消失）":"TIANJIANG_DYNAMICNPC_TIMELIMIT",
              "玩家#00FF00%s#FFFFFF击杀#00FF00%s#FFFFFF触怒#00FF00%s#FFFFFF":"TIANJIANG_DYNAMICNPC_LEADER",
              "CD时间冷却中":"CDING",
              "挑战次数已用完":"OUTOFCHALLENGECOUNT",
              "你想跟自己玩左右互搏吗……":"SELFPLAY",
              "您已威震本服，无人敢于应战":"UNSTOPPABLE",
              "金币或者奖杯不足":"NOMONEYORPOPULARITY",
              "训练等级已达到最高":"MAXTRAINLEVEL",
              "#fbc700%s#ffffff 训练【%s】+%d %s":"BROADCAST_MATETRAIN",
              "#00d03c成功#ffffff":"TRAIN_SUCCESS",
              "#ec0312失败#ffffff":"TRAIN_FAILD",
              "#fbc700%s#ffffff 成功击败  #fbc700%s#ffffff,成为竞技场新霸主!":"NEW_DOMINATOR",
              "#fbc700战斗力#ffffff  %s%d#ffffff":"ZHANDOULI",
              "#fbc700物理攻击#ffffff  %s%d#ffffff":"WULIGONGJI",
              "#fbc700物理防御#ffffff  %s%d#ffffff":"WULIFANGYU",
              "#fbc700法术攻击#ffffff  %s%d#ffffff":"FASHUGONGJI",
              "#fbc700法术防御#ffffff  %s%d#ffffff":"FASHUFANGYU",
              "#fbc700生命上限#ffffff  %s%d#ffffff":"SHENGMINGSHANGXIAN",
              "#fbc700命中等级#ffffff  %s%d#ffffff":"MINGZHONGDENGJI",
              "该活动奖励不存在":"XINFU_JIANGLI_BUNCUNZAI",
              "该活动已经过期":"XINFU_HUODONG_GUOQI",
              "该活动奖励已经领取":"XINFU_HUODONG_YIJING_LINGQU",
              "您的翅膀已经达到最大的数量":"CHIBANG_SHULIANG_ZUIDA",
              "所要激活的翅膀不存在":"WUFA_JIHUO_CHIBANG",
              "%d级以上才能挑战此副本":"FUBEN_LEVELLIMIT",
              "恭喜 #fbc700%s#ffffff 受到财神眷顾，天降#00d03c%d钻石#ffffff大礼！":"CAISHEN_DALI",
              "成功领取第%d名奖励":"PAIHANG_JIANGLI_LINGQU",
              "成功领取#00d03c%d钻石#ffffff":"LINGQU_ZUANSHI",
              "#fbc700%s#ffffff 人品爆发，擒获敌军将领：%s！":"RENPINBAOFA_MATE",
              "超过领取体力时间！":"OUTOFTIME_VIGORPRIZE",
              "恭喜获得#00d03c%d#ffffff点体力":"GET_VIGORPRIZE",
              "经验排行%d名外的新手玩家，每天额外赠送#00d03c%d#ffffff体力，努力升级吧！":"XINSHOU_FULI",
              "获得#00d03c%d#ffffff点体力":"DAILY_TILIPRIZE",
              "#fbc700%s#ffffff在竞技场疯狂杀戮,已经连胜#ec0312%d#ffffff次!":"JINGJI_SHALU_5",
              "#fbc700%s#ffffff在竞技场杀人如麻,已经连胜#ec0312%d#ffffff次!":"JINGJI_SHALU_6",
              "#fbc700%s#ffffff在竞技场大杀特杀,已经连胜#ec0312%d#ffffff次!":"JINGJI_SHALU_7",
              "#fbc700%s#ffffff在竞技场如同神一般,已经连胜#ec0312%d#ffffff次!":"JINGJI_SHALU_8",
              "#fbc700%s#ffffff在竞技场无人能挡,已经连胜#ec0312%d#ffffff次!":"JINGJI_SHALU_9",
              "#fbc700%s#ffffff主宰了竞技场,已经连胜#ec0312%d#ffffff次!":"JINGJI_SHALU_10",
              "#fbc700%s#ffffff 终结了 #fbc700%s#ffffff 在竞技场中的疯狂杀戮！":"JINGJI_ZHONGJIE_5",
              "#fbc700%s#ffffff 终结了 #fbc700%s#ffffff 在竞技场中的杀人如麻！":"JINGJI_ZHONGJIE_6",
              "#fbc700%s#ffffff 终结了 #fbc700%s#ffffff 在竞技场中的大杀特杀！":"JINGJI_ZHONGJIE_7",
              "#fbc700%s#ffffff 终结了 #fbc700%s#ffffff 在竞技场中如同神一般杀戮！":"JINGJI_ZHONGJIE_8",
              "#fbc700%s#ffffff 终结了 #fbc700%s#ffffff 在竞技场中的无人能挡！":"JINGJI_ZHONGJIE_9",
              "#fbc700%s#ffffff 终结了 #fbc700%s#ffffff 对竞技场的主宰！":"JINGJI_ZHONGJIE_10",
              "您已拥有了领地！":"TERRITORY_CAPTURE_ONLY_ONCE",
              "您没有拥有次领地！":"TERRITORY_NOT_OWN",
              "您包裹空间不够":"TERRITORY_BAOGUO_NOT_ENOUGH",
              "奖励领取成功":"TERRITORY_GET_PRIZE_SUC",
              "此领地已经属于你":"TERRITORY_YOU_OWN",
              "此领地无人占领":"TERRITORY_NOT_OWNER",
              "这领地太贫瘠了，换个地方看看吧":"TERRITORY_RES_TOO_LOW",              
              "#ff0000%s#ffffff掠夺#00ff00%s#ffffff的领地#00ff00%s#ffffff，获得#ffff00%d金币和%d奖杯":"TERRITORY_PLUNDER_SUC",
              "同一个玩家一个小时内只能掠夺一次":"TERRITORY_TIME_LIMIT",
              "一个小时内只能强行占领一次":"TERRITORY_FORCE_CAPTURE_TIME_LIMIT",
              "没有领地奖励可以领取":"TERRITORY_NOT_PRIZE",
              "您今日的领地奖励掠夺次数已达到上限":"TERRITORY_PLUNDER_TIMES_LIMIT",
              "#00ff00%s#ffffff成功攻占领地#00ff00%s":"TERRITORY_CAPTURE_SUC",
              "#ff0000%s#ffffff打败#00ff00%s#ffffff，成功攻占领地#00ff00%s":"TERRITORY_FORCE_CAPTURE_SUC",
              "暂时找不到该玩家的信息":"ROLE_NOT_FOUND",
              "正在努力查找信息中...":"LOADING",
              "对方拒绝与您战斗":"ROLE2ROLEPK_REFUSE",
              "无法与该玩家切磋":"ROLE2ROLEPK_CANT",
              "对方已经取消了战斗":"ROLE2ROLEPK_CANCEL",
              "对方正在与他人战斗中":"ROLE2ROLEPK_FIGHTING",
              "获得五星评论奖励#00d03c%d#ffffff钻石":"REPUTATION_PRIZE",
              "恭喜 #fbc700%s#ffffff 合成出 %s，球员属性大幅度提升！":"COMPOUNDEQUIPMENT_CONGRATULATION",
              "恭喜玩家 #fbc700%s#ffffff 完成日常连环，他的记录是#00d03c%d#ffffff小时#00d03c%d#ffffff分#00d03c%d#ffffff秒！等着你超越！":"DAILYLOOPTASK_CONGRATULATION",
              "恭喜玩家 #fbc700%s#ffffff 完成国家连环，他的记录是#00d03c%d#ffffff小时#00d03c%d#ffffff分#00d03c%d#ffffff秒！等着你超越！":"WEEKLYLOOPTASK_CONGRATULATION",
              "恭喜玩家 #fbc700%s#ffffff的【%s】球员进化到#00d03c%d#ffffff星球员，球员队伍实力大增！":"MATEENVOLVED_CONGRATULATION",
              "自动战斗时间已用完...":"AUTOFIGHT_OUTTIME",
              "今日可购买次数已使用完...":"OUTOFBUYCOUNT",
              "经验不足":"JINGYAN_BUZU",
              "经验或奖杯不足":"JINGYAN_HUO_SHENGWANG_BUZU",
              "已达到完美形态":"YIJING_DADAO_WANMEI_XINGTAI",
              "#00d03c成功！":"WING_CHENGGONG",
              "#ff0000失败……":"WING_SHIBAI",
              "#fbc700%s#ffffff的灵翅【%s】#ffffff进阶+%d %s":"LINGCHI_JINJIE",
              "对方正忙，请稍后再邀请":"ALREADYDOING",
              "对方已经组队了":"ALREADYTEAMED_OTHERS",
              "您已经有队伍了":"ALREADYTEAMED_SELF",
              "对方拒绝了您的组队请求":"REFUSE_MAKETEAM",
              "对方已取消组队请求":"CANCEL_MAKETEAM",
              "未找到队伍信息":"TEAM_INFO_NOT_FOUND",
              "组队状态下无法进入":"TEAM_CANT_SHOW_FIGHT", 
              "队员战斗阵型为空，请在阵型中配置出战的伙伴再来挑战吧！": "TEAM_MEMBER_FIGHTARRAY_EMPTY",
              "#fbc700%s#ffffff加入队伍":"JOINTEAM",
              "#fbc700%s#ffffff离开了队伍":"LEAVETEAM",
              "队伍人数已满":"OUTOFTEAMCOUNT",
              "#fbc700%s#ffffff成为了队长":"CHANGECAPTION_TEAM",
              "#fbc700%s#ffffff解散了队伍":"BREAK_TEAM",
              "您处在队伍中，请跟随队长的脚步...":"FOLLOWCAPTION",
              "名字中含有非法字符哦，请使用数字，字母，或者汉字吧":"MINGZI_FEIFA_ZIFU",
              "加入队伍失败":"FAIL_JOIN_TEAM",
              "只有队长才能进行该操作":"INVALID_TEAM_OPERATE",
              "等级已经达到上限，无法获得经验。":"TO_MAXLEVEL",
              "经验量已达存储上限，无法继续获得经验。":"EXP_TOOMORE",
              "不能装备相同属性的武魂":"NO_WEARSAMETYPE_WUSOUL",
              "升级所需精髓不足无法升级":"LEVELUP_NEEDITEM_NOTENOUGH",
              "#FFFF00%s#FFFFFF达到%d级领取等级奖励#A001FC%s#FFFFFF，羡慕吧？赶快升级吧！":"DENGJI_JIANGLI",
              "您今日还有未用完的剩余战斗时间！":"AUTOFIGHT_TIME",
              "获得武魂%s%s#FFFFFF%d个":"JIANGLI_WUHUN",
              "武魂已经达到最高等级，无法继续提升":"WUSOUL_CANNOTSTRENGTHEN",
              "武魂格子未解锁或无可装备格子":"WUSOUL_NOTGRIDCANWAER",
              "包裹中不存在武魂":"NO_WUSOUL_INPACKET",
              "#fbc700初始怒气#ffffff  %s%d#ffffff":"CHUSHINUQI",
              "球员领导力总和超过%d上限！":"MT_INVALID_LEADER_FORCE",
              "密码错误，请重新输入！":"DENGLU_MIMA_CUOWU",
              "账号不存在，请确认！":"DENGLU_ZHANGHAO_BUCUNZAI",
              "#fbc700%s#ffffff没有选择附体球员，不会进行攻击":"TEAM_NO_APPENDAGEMATE",
              "队员#fbc700%s#ffffff不符合进入该副本的条件!":"TEAM_MEMBER_CANTENTERFUBEN",
              "组队状态下无法进入万魔塔...":"CANT_ENTER_INTEAM",
              "组队状态下无法进入该副本...":"CANT_ENTER_FUBEN_TEAM",
              "组队状态下无法进入竞技场战斗":"CANT_CHALLENGE_TEAM",
              "恭喜#fbc700%s#ffffff荣升%s%s#ffffff爵位，指挥球员能力大幅提升！":"NOBILITY_LEVELUP",
              "#fbc700%s#ffffff在竞技排行不幸跌出前%d名，失去了%s%s#ffffff爵位……":"NOBILITY_LEVELDOWN",
              "只能与#ec0312%d#ffffff级以上玩家进行组队!":"TEAM_LEVELLIMIT",
              "您当前阵型无附体球员...":"TEAM_NO_APPENDAGEMATE_ARRAY",                 
              "找不到伙伴":"CANNOT_FIND_MATE",
              "无法学习相同的技能":"CANNOT_LEARN_SAMESKILL",            
              "重置所需道具不足":"RESETITEM_NOT_ENOUGH",             
              "进化之后才可以转化":"YUANSHEN_TAIDUO",
              "阵型当中的球员无法转化":"MATE_CANNOT_COMPOUND",
              "#00FF00%s#FFFFFF现身失落之城，各路英雄快去帮忙驱逐魔障！":"BOSS_CREATE", 
              "您当前的状态无法攻击魔障":"BOSS_CANTATK_BOSS",
              "您当前的状态无法攻击玩家":"BOSS_CANTATK_ROLE",
              "魔障副本未开启":"BOSS_CLOSED",
              "您不在魔障副本中":"BOSS_OUT_FUBEN",
              "该玩家已不再争夺所有权":"BOSS_NOT_ROBBING",
              "已经有人先你一步争夺中！":"BOSS_ALREADYROBBING",
              "对方正在战斗中...":"BOSS_FIGHTING",
              "副本中无法组队......":"TEAM_INFUBEN",     
              "%s意志不足":"YUANSHEN_BUZU",
              "无法攻击处于该状态的玩家":"BOSS_CANT_ATK_ROLE",
              "您的状态无法完成该操作":"BOSS_CANT_DOIT",
              "%s%s#ffffff成功被击杀，恭喜#fbc700%s#ffffff获得%s%s#ffffff碎片%d个！":"BOSS_AWARD_WUPIN",
              "%s%s#ffffff成功被击杀，#fbc700%s#ffffff天威浩荡，%s%s#ffffff前往投奔，球员队伍实力大增！":"BOSS_AWARD_MATE",
              "英明神武的 #fbc700 %s #ffffff创建了帮派 #fbc700 %s":"GANG_CREATE_BROADCAST",
              "该名字已经被使用!":"MINGZI_CHONGFU",              
              "ios7即将发布,请玩家暂时不要更新至ios7,否则有可能无法正常游戏.如发现问题请联系客服以及官方qq群246764348":"IOS7_JINJITONGGAO",
              "抱歉,ios7用户暂时无法登陆游戏":"IOS7_WUFADENGLU",
              "找不到该玩家":"ZHAOBUDAO_WANJIA",
              "该玩家处于偷袭保护期":"WANJIA_CHUYU_BAOHUQI",
              "偷袭限制时间还未结束，无法偷袭":"WANJIA_TOUXI_CDMEIJIESHU",
              "#fbc700%s#ffffff vs #fbc700%s#ffffff, 比分为#00FF00%d#FFFFFF:#00FF00%d#FFFFFF 此次帮派战的获胜者是#fbc700%s#ffffff 帮! #fbc700%s#ffffff 帮损失大量帮派资金!":"GANGFIGHT_RESULT",
              "未找到帮派信息":"GANG_NOTFOUND",
              "#fbc700%s#ffffff帮向#fbc700%s#ffffff帮发起了帮战，非战斗人员迅速撤离，不明真相的观众赶紧围观了！":"GANGFIGHT_START",
              "你们帮派之间没有开战，群众敬请围观就好！":"GANGFIGHT_NOTMATCH",
              "战斗状态无法打断...":"GANGFIGHT_ISFIGHTING",
              "#fbc700%s#ffffff帮的#00FF00%s#FFFFFF将#fbc700%s#ffffff帮的帮主#00FF00%s#FFFFFF斩于马下，帮派士气大振！ #fbc700%s#ffffff(#00FF00%d#FFFFFF):(#00FF00%d#FFFFFF)#fbc700%s#ffffff":"GANGFIGHT_LEADER_KILLED",
              "#fbc700%s#ffffff帮的#00FF00%s#FFFFFF将#fbc700%s#ffffff帮的副帮主#00FF00%s#FFFFFF斩于马下，帮派士气大振！ #fbc700%s#ffffff(#00FF00%d#FFFFFF):(#00FF00%d#FFFFFF)#fbc700%s#ffffff":"GANGFIGHT_VICELEADER_KILLED",
              "#fbc700%s#ffffff帮的#00FF00%s#FFFFFF击杀了#fbc700%s#ffffff帮的#00FF00%s#FFFFFF！ #fbc700%s#ffffff(#00FF00%d#FFFFFF):(#00FF00%d#FFFFFF)#fbc700%s#ffffff":"GANGFIGHT_MEMBER_KILLED",
              "帮派已经处于战斗状态":"GANGFIGHT_ALREADY",
              "你被#fbc700%s#ffffff偷袭，损失%d点经验":"BEFORCEKILL_SUCCESS",
              "你偷袭#fbc700%s#ffffff失败，反被#fbc700%s#ffffff羞辱，损失%d点经验":"FORCEKILL_FAIL",
              "你偷袭#fbc700%s#ffffff成功，#fbc700%s#ffffff损失%d点经验":"FORCEKILL_SUCCESS",
              "#fbc700%s#ffffff偷袭你失败，偷鸡不成蚀把米他损失%d点经验":"FORCEKILL_COUNTERKILL",
              "你正在自动战斗中，无法偷袭":"ISAUTOFIGHTING_CANTFORCEKILL",
              "目标玩家正在自动战斗中，无法偷袭":"TARGETROLE_ISAUTOFIGHTING",
              "战斗状态无法打断...":"GANGFIGHT_ISFIGHTING",
              "组队状态无法偷袭":"CANFORCEKILL_INTEAM",
              "当前阵型未设置出战球员，请设置阵型。":"FIGHT_ARRAY_EMPTY",
              "#fbc700%s#ffffff帮在帮战中被敌方打的溃不成军，居然解散了帮派，你敢信？":"GANGFIGHT_DISMISS",
              "很抱歉，半价活动已结束……":"ACTIVITY_HALF_PRICE_OVER",
              "本服暂停注册,请选择其他服":"BENFU_ZANTINGZHUCE",
              "帮会建设任务开启失败!":"START_GANGCONSTRUCT_ERROR",
              "今天帮会建设任务已开启两次！":"GANGCONSTRUCT_TWOTIMES",
              "帮会建设任务已经开启！":"GANGCONSTRUCT_STARTED",
              "副帮主以上职位才能开启！":"ATLEAST_E_Gang_Identity_ViceLeader",
              "没有可完成的任务！":"GANGTASK_NONEEDDIAMOND",
              "帮派资金不足":"GANG_GLOD_NOTENOUGH",
              "玩家不存在或玩家不在线":"WANJIABUCUNZAI_BUZAIXIAN",
              "对方可结拜好友已达到上限":"BROTHERS_TO_UPPERLIMIT",
              "请求玩家已不在线，结拜失败":"SENDER_NOTONLINE",
              "等级不足或者没有充值过任意金额，无法结拜":"CONDITION_LEVEL_NOT_ENOUGH",
              "绝交惩罚时间未结束或者对方绝交惩罚时间未结束，无法结拜":"BREAKOFF_TIME_NOT_FINISH",
              "对方等级不足或者没有充值过任意金额，无法结拜":"TARGET_CONDITION_LEVEL_NOT_ENOUGH",
              "你还有%d小时后结束绝交惩罚":"BREAKOFF_REMAIN_TIME",
              "对方拒绝与你结拜":"REJECT_BECOME_BROTHERS",
              "不能与自己结拜":"CANNOT_BECOMEBROTHERS_WITHSELF",
              "结拜朋友#ffffff充值%d元，沾光获得#00D03C%d钻石#ffffff奖励！%s":"BROTHERS_BOON_DESC",
              "请领取完结拜好友的福利之后才进行绝交操作":"CANNOTBREAKOFF_BECAUSE_HAVE_BOON",
              "由于#fbc700%s#ffffff已经跟你绝交，你的结拜好友福利#00D03C%d钻石#ffffff已经自动领取":"BREAKOFF_AUTO_GETBOON",
              "恭喜，你与#fbc700%s#ffffff玩家结拜成功！":"BECOMEBROTHERS_SUCCESS",
              "充值达到%d元赠送您：%s":"BUSINESS_RECHARGE_TOTAL_PRIZETEXT",
              "帮会资金增加%d":"GANG_ZIJIN_ADD",
              "帮会人气增加%d":"GANG_POPULARITY_ADD",
              "帮会贡献增加%d":"GANG_CONTRIBUTION_ADD",
              "限量灵翅已经售完!":"OPERATEPRIZE_LIMITED_WING",
              "未达到领取条件":"OPERATEPRIZE_IAP_WING_CANT",
              "苍天有眼,出现稀有资质!":"RESET_TO_RARE_APTITUDE",
              "福利已经领取完毕，无法再次领取。":"BROTHERS_PRIZE_HAVE_DONE",
              "、":"AWARDITEM_SEMICOLON",
              "你已领取过奖励！":"AWARD_HAD_GET",
              "活动正在进行中，请等待结束后领取奖励。":"ACTIVITY_ON_WAY_NOW",
              "你不在这个排名，无法领取该排名的奖励":"NOT_IN_RANKING",
              "条件不足，无法领取奖励！":"ARG_NOT_ENOUGH",
              "物品已满无法获得奖励":"ITEM_FULL_CANNOT_GETPRIZE",
              "球员位已满，无法获得球员":"MATE_FULL_CANNOT_GETPRIZE",
              "、%s%s#FFFFFF%d个":"OPERATEPRIZE_GET_FRAGMENT",
              "该球员只能钻石招募":"ONLY_RECRUIT_BY_DIAMOND",
              "是":"PANDUAN",
              "#fbc700%s#ffffff冲上了充值排行榜第#fbc700%d#ffffff名，#fbc700%d#ffffff强之间竞争激烈！":"RECHARGE_BROADCAST_MSG_4_10",
              "#ffffff恭喜#fbc700%s#ffffff一举夺得了充值排行榜第#fbc700%d#ffffff名，最终第%d名花落谁家我们拭目以待！":"RECHARGE_BROADCAST_MSG_1",
              "#fbc700%s#ffffff冲上了充值排行第#fbc700%d#ffffff名，竞争已到火热化阶段！":"RECHARGE_BROADCAST_MSG_2_3",
              "【奖励】恭喜您获得第#00d03c%d#ffffff名奖励 奖励物品有:%s":"RANK_RECHARGE_AWARD",
              "玩家不存在！":"ROLE_NOT_EXIST",
              "您已经拥有魔障归属权":"BOSS_ALREADY_BELONG",
              "次数不足无法进入%s副本":"FUBEN_REMAIN_COUNT_NOT_ENOUGH",
              "财源滚滚！%s连续%d天圆满完成帮会日常任务，获得%d倍奖励#00FF00%d万#FFFFFF金币！":"SHIBEI_GANG_Prize",
              "活动领奖时间已结束，系统自动为您发放奖励!":"GETPRIZE_TIMEOUT_AUTOGETPRIZE",
              "%d个":"NUMBER_CHIESE_LINK",
              "你自恋吗？连自己都想加？":"CAN_ADDFRIEND_TO_SELF",
              "对方已经是你的好友":"TARGET_ISYOUR_FRIEND",
              "好友已达上限":"FRIENDNUMBER_TO_LIMIT",
              "已经发出申请，等待玩家回复":"ALREADY_SEND_APPLY",
              "活动[#fbc700%s#ffffff]正在进行中":"SYSTEM_MSG_ACTIVITYONLINENOW",
              "等级需达到#00d03c%d#ffffff级才可以转化元神":"LEVEL_TO_HIGHEST_YUANSHEN",
              "获得：%s":"GETPRIZE_TIMEOUT_AUTOGETPRIZE_ADDSTR",
              "#fbc700%s#ffffff玩家成功领取了豪华首冲奖励获得了神级球员#a001fc孙尚香#ffffff，#036cfb白虎武魂#ffffff，#036cfb高级技能书随机券#ffffff，#a001fc高级经验药水#ffffff5个，#a001fc资质丸#ffffff30个！":"GET_FIRSTCHARGE_BOARTMSG",
              "金币#00FF00%d#FFFFFF":"FIX_GIFT_JINBI_MODULE",
              "%s%d个":"FIX_GIFT_WUPIN_GREATE_ONE",
              "#FFFFFF天赐好礼，%s开启%s获得了":"FIX_GIFT_SCROLLBAR_BRODCAST", #第一个%s是名字，第二个%s是固定礼包的名字，第三个%s是所有奖品组合的结果
              "天赐好礼，%s开启%s获得了":"FIX_GIFT_SYSBRODCAST",
              "#FF0000注意！#FFFFFF#00FF00%d小时#FFFFFF#FF0000后帮派资金没有恢复为正数，则帮派会被强制解散！":"GANG_DISMISSING",
              "已经是好友！":"ALREADY_FRIEND",
              "你是申请者！":"YOU_IS_REQER",
              "本服顶级高富帅#fbc700%s#ffffff豪夺充值排行冠军，获得奖励%s":"RANKOFRECHARGE_FIRST_AWARDMSG",
              "#fbc700%s#ffffff富甲天下荣登充值排行亚军，获得奖励%s":"RANKOFRECHARGE_SECOND_AWARDMSG",
              "#fbc700%s#ffffff名扬四方夺得充值排行季军，获得奖励%s":"RANKOFRECHARGE_THIRD_AWARDMSG",
              "条件不足无法升级":"CODITION_NOT_ENOUGH_CANNOT_LEVELUP",
              "帮派等级已达到满级，无法升级":"GANGLEVEL_TO_LIMIT",
              "#fbc700%s#ffffff和#fbc700%s#ffffff义结金兰，有难同当，有钻同享。只享不冲，客服共愤。（结拜后一人充值，另一人获得%d%%钻石馈赠）":"BECOMEBROTHER_NOTE",
              "购买失败":"BUY_FAILURE",
              "已经拥有了该翅膀":"WING_ALREADY_HAVE",
              "充值排行榜活动再次开启，系统为您发放上次活动奖励":"GETPRIZE_OUTTIME_RANKOFRECHARGE",
              "无法解雇拥有紫色装备以上的球员！":"DISMISSMATE_HAVE_CANNOT_ARG",
              "#FFFFFF万众瞩目，#00FF00%s#FFFFFF成功合成出稀有灵翅%s":"WING_NEWOEPRATE",
              "钻石x%d":"PAY_DIAMOND",
              "今天的新手登陆奖励已经领取，无法多次领取！":"AWARD_HAVE_RECEIVE",
              "%s剩余#00d03c%d#ffffff钻石待领取%s":"REMAIN_BROTHERS_BOON",
              "，可领取#00d03c%d#ffffff钻石":"CAN_GAINREMAIN_BOON",
              "洽谈已经结束":"DISCUSS_IS_OVER",
              "洽谈条件不满足":"DISCUSS_CONDITION_NOT_ENOUGHT",
              "好感度已满":"GOOD_VALUE_ENOUGHT",
              "物品位已满":"ITEM_HAD_FULL",
              "奖杯不足":"CUP_NOT_ENOUGH",
              "#fbc700射门#ffffff  %s%d#ffffff":"SHEMEN",
              "#fbc700平衡#ffffff  %s%d#ffffff":"PINGHENG",
              "#fbc700控球#ffffff  %s%d#ffffff":"KONGQIU",
              "#fbc700传球#ffffff  %s%d#ffffff":"CHUANQIU",
              "#fbc700干扰#ffffff  %s%d#ffffff":"GANRAO",
              "#fbc700侵犯#ffffff  %s%d#ffffff":"QINFAN",
              "#fbc700抢断#ffffff  %s%d#ffffff":"QIANGDUAN",
              "#fbc700拦截#ffffff  %s%d#ffffff":"LANJIE",
              "#fbc700扑救#ffffff  %s%d#ffffff":"PUQIU",
              "#fbc700手控球#ffffff  %s%d#ffffff":"SHOUKONGQIU",
              "#fbc700速度#ffffff  %s%d#ffffff":"SHUDU",
              "该教练已经执教":"EXIST_COACH_SERVER",
              "测试角色":"TEST_ROLE",
              "传奇巨星":"CHUANQIJUXING",
              "超级偶像":"CHAOJIOUXIANG",
              "任务类型错误":"TASK_TYPE_ERROR",
              "任务还未完成":"TASK_NO_COMPLETE",
              "任务不存在":"TASK_NO_EXSIT",
              "#ffffff%s %d/%d":"TASK_HELP_TIP",
              "#00d03c%s 已完成":"TASK_COMPLETE_TIP",
              "获得%d金币":"BUYGOLD_SUCCESSTIP",

              "欢迎来到脑洞大开":"HUANYING_NDDK",
              "教室":"JIAOSHI",
              "操场":"CAOCHANG",
              "大门":"DAMEN",
              "食堂":"SHITANG",
              "加载中...":"TISHI_JIAZAIZHONG",
              "正在连接服务器...":"TISHI_ZHENGZAI_LIANJIE_FUWUQI",
              "正在验证帐号...":"TISHI_ZHENGZAI_YANZHENG_ZHANGHAO",
              "正在创建角色...":"TISHI_ZHENGZAI_CHUANGJIAN_JUESE",
              "失去连接..":"TISHI_SHIQU_LIANJIE",
                            }
"""
增加日志：玩家获得和失去以下东西有记录：物品（含装备、图纸、碎片等可以放入背包的东西）、球员、金钱、钻石"""

def fun_buildMsg(chinese):
    s = chinese.encode('utf8')
    s2 = """%r"""%(s)
    s2 = s2[1:-1]
    global g_msg_define
    define = g_msg_define[chinese]
    return """#define %(define)s "%(s2)s"\n//%(s)s\n"""%(locals())

def main():
    global g_msg_define
    file_template = """#ifndef __UTF8_WORDS_HLP_H__
#define    __UTF8_WORDS_HLP_H__
%s
#endif
"""
    w = open('../Common/Configure/Utf8WordsHlp.h', 'w')
    #w = open('testSqlOperationHlp.h', 'w')
    str = string.join(map(fun_buildMsg, g_msg_define.keys()), '\n')
    str = file_template%str
    str = str.encode("gbk")
    w.write(str)
    w.close()
    
    w = open('../server/common_interface/Utf8WordsHlp.h', 'w')
    #w = open('testSqlOperationHlp.h', 'w')
    str = string.join(map(fun_buildMsg, g_msg_define.keys()), '\n')
    str = file_template%str
    str = str.encode("gbk")
    w.write(str)
    w.close()

main()
print "OK"