// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers


struct PROPERTY_TYPE_FirstAgent_localCanshu { };
template<> inline int& FirstAgent::_Get_Property_<PROPERTY_TYPE_FirstAgent_localCanshu>()
{
	return this->localCanshu;
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
