// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_GENERATED_BEHAVIORS_H_
#define _BEHAVIAC_GENERATED_BEHAVIORS_H_

#include "../types/behaviac_types.h"

namespace behaviac
{
	// Source file: selectorprobabilityBT

	class SelectorProbability_bt_selectorprobabilityBT_node0 : public SelectorProbability
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(SelectorProbability_bt_selectorprobabilityBT_node0, SelectorProbability);
		SelectorProbability_bt_selectorprobabilityBT_node0()
		{
		}
	public:
		void Initialize(const char* method)
		{
			this->m_method = AgentMeta::ParseMethod(method);
		}
	};

	class DecoratorWeight_bt_selectorprobabilityBT_node4 : public DecoratorWeight
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(DecoratorWeight_bt_selectorprobabilityBT_node4, DecoratorWeight);
		DecoratorWeight_bt_selectorprobabilityBT_node4()
		{
			m_bDecorateWhenChildEnds = false;
		}
	protected:
		virtual int GetWeight(Agent* pAgent) const
		{
			BEHAVIAC_UNUSED_VAR(pAgent);
			return 20;
		}
	};

	class Action_bt_selectorprobabilityBT_node1 : public Action
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(Action_bt_selectorprobabilityBT_node1, Action);
		Action_bt_selectorprobabilityBT_node1()
		{
			method_p0 = (char*)("A");
		}
	protected:
		virtual EBTStatus update_impl(Agent* pAgent, EBTStatus childStatus)
		{
			BEHAVIAC_UNUSED_VAR(pAgent);
			BEHAVIAC_UNUSED_VAR(childStatus);
			((FirstAgent*)pAgent)->Say(method_p0);
			return BT_SUCCESS;
		}
		behaviac::string method_p0;
	};

	class DecoratorWeight_bt_selectorprobabilityBT_node5 : public DecoratorWeight
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(DecoratorWeight_bt_selectorprobabilityBT_node5, DecoratorWeight);
		DecoratorWeight_bt_selectorprobabilityBT_node5()
		{
			m_bDecorateWhenChildEnds = false;
		}
	protected:
		virtual int GetWeight(Agent* pAgent) const
		{
			BEHAVIAC_UNUSED_VAR(pAgent);
			return 30;
		}
	};

	class Action_bt_selectorprobabilityBT_node2 : public Action
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(Action_bt_selectorprobabilityBT_node2, Action);
		Action_bt_selectorprobabilityBT_node2()
		{
			method_p0 = (char*)("B");
		}
	protected:
		virtual EBTStatus update_impl(Agent* pAgent, EBTStatus childStatus)
		{
			BEHAVIAC_UNUSED_VAR(pAgent);
			BEHAVIAC_UNUSED_VAR(childStatus);
			((FirstAgent*)pAgent)->Say(method_p0);
			return BT_SUCCESS;
		}
		behaviac::string method_p0;
	};

	class DecoratorWeight_bt_selectorprobabilityBT_node6 : public DecoratorWeight
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(DecoratorWeight_bt_selectorprobabilityBT_node6, DecoratorWeight);
		DecoratorWeight_bt_selectorprobabilityBT_node6()
		{
			m_bDecorateWhenChildEnds = false;
		}
	protected:
		virtual int GetWeight(Agent* pAgent) const
		{
			BEHAVIAC_UNUSED_VAR(pAgent);
			return 50;
		}
	};

	class Action_bt_selectorprobabilityBT_node3 : public Action
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(Action_bt_selectorprobabilityBT_node3, Action);
		Action_bt_selectorprobabilityBT_node3()
		{
			method_p0 = (char*)("C");
		}
	protected:
		virtual EBTStatus update_impl(Agent* pAgent, EBTStatus childStatus)
		{
			BEHAVIAC_UNUSED_VAR(pAgent);
			BEHAVIAC_UNUSED_VAR(childStatus);
			((FirstAgent*)pAgent)->Say(method_p0);
			return BT_SUCCESS;
		}
		behaviac::string method_p0;
	};

	class bt_selectorprobabilityBT
	{
	public:
		static bool Create(BehaviorTree* pBT)
		{
			pBT->SetClassNameString("BehaviorTree");
			pBT->SetId((uint16_t)-1);
			pBT->SetName("selectorprobabilityBT");
			pBT->SetIsFSM(false);
#if !BEHAVIAC_RELEASE
			pBT->SetAgentType("FirstAgent");
#endif
			// children
			{
				SelectorProbability_bt_selectorprobabilityBT_node0* node0 = BEHAVIAC_NEW SelectorProbability_bt_selectorprobabilityBT_node0;
				node0->SetClassNameString("SelectorProbability");
				node0->SetId(0);
#if !BEHAVIAC_RELEASE
				node0->SetAgentType("FirstAgent");
#endif
				pBT->AddChild(node0);
				{
					DecoratorWeight_bt_selectorprobabilityBT_node4* node4 = BEHAVIAC_NEW DecoratorWeight_bt_selectorprobabilityBT_node4;
					node4->SetClassNameString("DecoratorWeight");
					node4->SetId(4);
#if !BEHAVIAC_RELEASE
					node4->SetAgentType("FirstAgent");
#endif
					node0->AddChild(node4);
					{
						Action_bt_selectorprobabilityBT_node1* node1 = BEHAVIAC_NEW Action_bt_selectorprobabilityBT_node1;
						node1->SetClassNameString("Action");
						node1->SetId(1);
#if !BEHAVIAC_RELEASE
						node1->SetAgentType("FirstAgent");
#endif
						node4->AddChild(node1);
						node4->SetHasEvents(node4->HasEvents() | node1->HasEvents());
					}
					node0->SetHasEvents(node0->HasEvents() | node4->HasEvents());
				}
				{
					DecoratorWeight_bt_selectorprobabilityBT_node5* node5 = BEHAVIAC_NEW DecoratorWeight_bt_selectorprobabilityBT_node5;
					node5->SetClassNameString("DecoratorWeight");
					node5->SetId(5);
#if !BEHAVIAC_RELEASE
					node5->SetAgentType("FirstAgent");
#endif
					node0->AddChild(node5);
					{
						Action_bt_selectorprobabilityBT_node2* node2 = BEHAVIAC_NEW Action_bt_selectorprobabilityBT_node2;
						node2->SetClassNameString("Action");
						node2->SetId(2);
#if !BEHAVIAC_RELEASE
						node2->SetAgentType("FirstAgent");
#endif
						node5->AddChild(node2);
						node5->SetHasEvents(node5->HasEvents() | node2->HasEvents());
					}
					node0->SetHasEvents(node0->HasEvents() | node5->HasEvents());
				}
				{
					DecoratorWeight_bt_selectorprobabilityBT_node6* node6 = BEHAVIAC_NEW DecoratorWeight_bt_selectorprobabilityBT_node6;
					node6->SetClassNameString("DecoratorWeight");
					node6->SetId(6);
#if !BEHAVIAC_RELEASE
					node6->SetAgentType("FirstAgent");
#endif
					node0->AddChild(node6);
					{
						Action_bt_selectorprobabilityBT_node3* node3 = BEHAVIAC_NEW Action_bt_selectorprobabilityBT_node3;
						node3->SetClassNameString("Action");
						node3->SetId(3);
#if !BEHAVIAC_RELEASE
						node3->SetAgentType("FirstAgent");
#endif
						node6->AddChild(node3);
						node6->SetHasEvents(node6->HasEvents() | node3->HasEvents());
					}
					node0->SetHasEvents(node0->HasEvents() | node6->HasEvents());
				}
				pBT->SetHasEvents(pBT->HasEvents() | node0->HasEvents());
			}
			return true;
		}
	};

	// Source file: selectorstochasticBT

	class SelectorStochastic_bt_selectorstochasticBT_node0 : public SelectorStochastic
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(SelectorStochastic_bt_selectorstochasticBT_node0, SelectorStochastic);
		SelectorStochastic_bt_selectorstochasticBT_node0()
		{
		}
	public:
		void Initialize(const char* method)
		{
			this->m_method = AgentMeta::ParseMethod(method);
		}
	};

	class Action_bt_selectorstochasticBT_node1 : public Action
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(Action_bt_selectorstochasticBT_node1, Action);
		Action_bt_selectorstochasticBT_node1()
		{
			method_p0 = (char*)("A");
		}
	protected:
		virtual EBTStatus update_impl(Agent* pAgent, EBTStatus childStatus)
		{
			BEHAVIAC_UNUSED_VAR(pAgent);
			BEHAVIAC_UNUSED_VAR(childStatus);
			((FirstAgent*)pAgent)->Say(method_p0);
			return BT_SUCCESS;
		}
		behaviac::string method_p0;
	};

	class Action_bt_selectorstochasticBT_node2 : public Action
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(Action_bt_selectorstochasticBT_node2, Action);
		Action_bt_selectorstochasticBT_node2()
		{
			method_p0 = (char*)("B");
		}
	protected:
		virtual EBTStatus update_impl(Agent* pAgent, EBTStatus childStatus)
		{
			BEHAVIAC_UNUSED_VAR(pAgent);
			BEHAVIAC_UNUSED_VAR(childStatus);
			((FirstAgent*)pAgent)->Say(method_p0);
			return BT_SUCCESS;
		}
		behaviac::string method_p0;
	};

	class Action_bt_selectorstochasticBT_node3 : public Action
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(Action_bt_selectorstochasticBT_node3, Action);
		Action_bt_selectorstochasticBT_node3()
		{
			method_p0 = (char*)("C");
		}
	protected:
		virtual EBTStatus update_impl(Agent* pAgent, EBTStatus childStatus)
		{
			BEHAVIAC_UNUSED_VAR(pAgent);
			BEHAVIAC_UNUSED_VAR(childStatus);
			((FirstAgent*)pAgent)->Say(method_p0);
			return BT_SUCCESS;
		}
		behaviac::string method_p0;
	};

	class bt_selectorstochasticBT
	{
	public:
		static bool Create(BehaviorTree* pBT)
		{
			pBT->SetClassNameString("BehaviorTree");
			pBT->SetId((uint16_t)-1);
			pBT->SetName("selectorstochasticBT");
			pBT->SetIsFSM(false);
#if !BEHAVIAC_RELEASE
			pBT->SetAgentType("FirstAgent");
#endif
			// children
			{
				SelectorStochastic_bt_selectorstochasticBT_node0* node0 = BEHAVIAC_NEW SelectorStochastic_bt_selectorstochasticBT_node0;
				node0->SetClassNameString("SelectorStochastic");
				node0->SetId(0);
#if !BEHAVIAC_RELEASE
				node0->SetAgentType("FirstAgent");
#endif
				pBT->AddChild(node0);
				{
					Action_bt_selectorstochasticBT_node1* node1 = BEHAVIAC_NEW Action_bt_selectorstochasticBT_node1;
					node1->SetClassNameString("Action");
					node1->SetId(1);
#if !BEHAVIAC_RELEASE
					node1->SetAgentType("FirstAgent");
#endif
					node0->AddChild(node1);
					node0->SetHasEvents(node0->HasEvents() | node1->HasEvents());
				}
				{
					Action_bt_selectorstochasticBT_node2* node2 = BEHAVIAC_NEW Action_bt_selectorstochasticBT_node2;
					node2->SetClassNameString("Action");
					node2->SetId(2);
#if !BEHAVIAC_RELEASE
					node2->SetAgentType("FirstAgent");
#endif
					node0->AddChild(node2);
					node0->SetHasEvents(node0->HasEvents() | node2->HasEvents());
				}
				{
					Action_bt_selectorstochasticBT_node3* node3 = BEHAVIAC_NEW Action_bt_selectorstochasticBT_node3;
					node3->SetClassNameString("Action");
					node3->SetId(3);
#if !BEHAVIAC_RELEASE
					node3->SetAgentType("FirstAgent");
#endif
					node0->AddChild(node3);
					node0->SetHasEvents(node0->HasEvents() | node3->HasEvents());
				}
				pBT->SetHasEvents(pBT->HasEvents() | node0->HasEvents());
			}
			return true;
		}
	};

	// Source file: sequencestochasticBT

	class SequenceStochastic_bt_sequencestochasticBT_node0 : public SequenceStochastic
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(SequenceStochastic_bt_sequencestochasticBT_node0, SequenceStochastic);
		SequenceStochastic_bt_sequencestochasticBT_node0()
		{
		}
	public:
		void Initialize(const char* method)
		{
			this->m_method = AgentMeta::ParseMethod(method);
		}
	};

	class Action_bt_sequencestochasticBT_node1 : public Action
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(Action_bt_sequencestochasticBT_node1, Action);
		Action_bt_sequencestochasticBT_node1()
		{
			method_p0 = (char*)("A");
		}
	protected:
		virtual EBTStatus update_impl(Agent* pAgent, EBTStatus childStatus)
		{
			BEHAVIAC_UNUSED_VAR(pAgent);
			BEHAVIAC_UNUSED_VAR(childStatus);
			((FirstAgent*)pAgent)->Say(method_p0);
			return BT_SUCCESS;
		}
		behaviac::string method_p0;
	};

	class Action_bt_sequencestochasticBT_node2 : public Action
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(Action_bt_sequencestochasticBT_node2, Action);
		Action_bt_sequencestochasticBT_node2()
		{
			method_p0 = (char*)("B");
		}
	protected:
		virtual EBTStatus update_impl(Agent* pAgent, EBTStatus childStatus)
		{
			BEHAVIAC_UNUSED_VAR(pAgent);
			BEHAVIAC_UNUSED_VAR(childStatus);
			((FirstAgent*)pAgent)->Say(method_p0);
			return BT_SUCCESS;
		}
		behaviac::string method_p0;
	};

	class Action_bt_sequencestochasticBT_node3 : public Action
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(Action_bt_sequencestochasticBT_node3, Action);
		Action_bt_sequencestochasticBT_node3()
		{
			method_p0 = (char*)("C");
		}
	protected:
		virtual EBTStatus update_impl(Agent* pAgent, EBTStatus childStatus)
		{
			BEHAVIAC_UNUSED_VAR(pAgent);
			BEHAVIAC_UNUSED_VAR(childStatus);
			((FirstAgent*)pAgent)->Say(method_p0);
			return BT_SUCCESS;
		}
		behaviac::string method_p0;
	};

	class bt_sequencestochasticBT
	{
	public:
		static bool Create(BehaviorTree* pBT)
		{
			pBT->SetClassNameString("BehaviorTree");
			pBT->SetId((uint16_t)-1);
			pBT->SetName("sequencestochasticBT");
			pBT->SetIsFSM(false);
#if !BEHAVIAC_RELEASE
			pBT->SetAgentType("FirstAgent");
#endif
			// children
			{
				SequenceStochastic_bt_sequencestochasticBT_node0* node0 = BEHAVIAC_NEW SequenceStochastic_bt_sequencestochasticBT_node0;
				node0->SetClassNameString("SequenceStochastic");
				node0->SetId(0);
#if !BEHAVIAC_RELEASE
				node0->SetAgentType("FirstAgent");
#endif
				pBT->AddChild(node0);
				{
					Action_bt_sequencestochasticBT_node1* node1 = BEHAVIAC_NEW Action_bt_sequencestochasticBT_node1;
					node1->SetClassNameString("Action");
					node1->SetId(1);
#if !BEHAVIAC_RELEASE
					node1->SetAgentType("FirstAgent");
#endif
					node0->AddChild(node1);
					node0->SetHasEvents(node0->HasEvents() | node1->HasEvents());
				}
				{
					Action_bt_sequencestochasticBT_node2* node2 = BEHAVIAC_NEW Action_bt_sequencestochasticBT_node2;
					node2->SetClassNameString("Action");
					node2->SetId(2);
#if !BEHAVIAC_RELEASE
					node2->SetAgentType("FirstAgent");
#endif
					node0->AddChild(node2);
					node0->SetHasEvents(node0->HasEvents() | node2->HasEvents());
				}
				{
					Action_bt_sequencestochasticBT_node3* node3 = BEHAVIAC_NEW Action_bt_sequencestochasticBT_node3;
					node3->SetClassNameString("Action");
					node3->SetId(3);
#if !BEHAVIAC_RELEASE
					node3->SetAgentType("FirstAgent");
#endif
					node0->AddChild(node3);
					node0->SetHasEvents(node0->HasEvents() | node3->HasEvents());
				}
				pBT->SetHasEvents(pBT->HasEvents() | node0->HasEvents());
			}
			return true;
		}
	};

	// Source file: assignBT

	class Assignment_bt_assignBT_node1 : public Assignment
	{
	public:
		BEHAVIAC_DECLARE_DYNAMIC_TYPE(Assignment_bt_assignBT_node1, Assignment);
		Assignment_bt_assignBT_node1()
		{
		}
	protected:
		virtual EBTStatus update_impl(Agent* pAgent, EBTStatus childStatus)
		{
			BEHAVIAC_UNUSED_VAR(pAgent);
			BEHAVIAC_UNUSED_VAR(childStatus);
			EBTStatus result = BT_SUCCESS;
			int opr = 99;
			((FirstAgent*)pAgent)->_Get_Property_<PROPERTY_TYPE_FirstAgent_localCanshu, int >() = opr;
			return result;
		}
	};

	class bt_assignBT
	{
	public:
		static bool Create(BehaviorTree* pBT)
		{
			pBT->SetClassNameString("BehaviorTree");
			pBT->SetId((uint16_t)-1);
			pBT->SetName("assignBT");
			pBT->SetIsFSM(false);
#if !BEHAVIAC_RELEASE
			pBT->SetAgentType("FirstAgent");
#endif
			// children
			{
				Sequence* node0 = BEHAVIAC_NEW Sequence;
				node0->SetClassNameString("Sequence");
				node0->SetId(0);
#if !BEHAVIAC_RELEASE
				node0->SetAgentType("FirstAgent");
#endif
				pBT->AddChild(node0);
				{
					Assignment_bt_assignBT_node1* node1 = BEHAVIAC_NEW Assignment_bt_assignBT_node1;
					node1->SetClassNameString("Assignment");
					node1->SetId(1);
#if !BEHAVIAC_RELEASE
					node1->SetAgentType("FirstAgent");
#endif
					node0->AddChild(node1);
					node0->SetHasEvents(node0->HasEvents() | node1->HasEvents());
				}
				pBT->SetHasEvents(pBT->HasEvents() | node0->HasEvents());
			}
			return true;
		}
	};

}
#endif // _BEHAVIAC_GENERATED_BEHAVIORS_H_
