// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#include "behaviac/behaviac.h"

#include "behaviac_generated_behaviors.h"

namespace behaviac
{
	class CppGenerationManager : GenerationManager
	{
	public:
		CppGenerationManager()
		{
			SetInstance(this);
		}

		virtual void RegisterBehaviorsImplement()
		{
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("selectorprobabilityBT", bt_selectorprobabilityBT::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("selectorstochasticBT", bt_selectorstochasticBT::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("sequencestochasticBT", bt_sequencestochasticBT::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("assignBT", bt_assignBT::Create);
		}
	};

	CppGenerationManager _cppGenerationManager_;
}
